"""Generate the proposed workbook contract for an external USLS AIMS export.

This workbook is a project proposal for review by the AIMS/Registrar owner. It
is not evidence that the current AIMS installation already exports this format.
"""

from __future__ import annotations

from pathlib import Path

from openpyxl import Workbook
from openpyxl.comments import Comment
from openpyxl.styles import Alignment, Border, Font, PatternFill, Protection, Side
from openpyxl.utils import get_column_letter


PROJECT_ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = (
    PROJECT_ROOT
    / "Documents"
    / "AIMS_Export"
    / "PROPOSED_USLS_AIMS_Export_Template.xlsx"
)

SCHEMA_VERSION = "PROPOSED-1.0"
OFFICIAL_PORTAL = "https://aims.usls.edu.ph/lasalle/"
OFFICIAL_GUIDE = "https://www.usls.edu.ph/uploads/posts/AIMS-2022/AIMS.pdf"

GREEN = "1F6B45"
PALE_GREEN = "E7F2EC"
PALE_YELLOW = "FFF4CC"
PALE_BLUE = "EAF2F8"
LIGHT_GRAY = "E7E6E6"
WHITE = "FFFFFF"
RED = "9C0006"
THIN_GRAY = Side(style="thin", color="B7B7B7")


SHEETS: dict[str, list[tuple[str, str, str, str]]] = {
    "Export_Metadata": [
        (
            "SCHEMA_VERSION",
            "Yes",
            "Text",
            f"Template/import-contract version. Use {SCHEMA_VERSION} until an approved version replaces it.",
        ),
        ("SOURCE_SYSTEM", "Yes", "Text", "Must identify AIMS as the external source system."),
        (
            "EXPORT_BATCH_ID",
            "Yes",
            "Text",
            "Unique identifier generated by the authorized exporting process or office.",
        ),
        (
            "EXPORTED_AT",
            "Yes",
            "ISO 8601 datetime",
            "Time the source export was generated, including time-zone offset.",
        ),
        (
            "EXPORT_SCOPE",
            "Yes",
            "Text",
            "Human-readable scope, such as the covered program, term, or full-history range.",
        ),
        (
            "EXPORTING_OFFICE",
            "Yes",
            "Text",
            "Authorized USLS office responsible for generating the export.",
        ),
        (
            "ACADEMIC_YEAR",
            "No",
            "Text",
            "Batch-level academic year when the file covers one year; preserve the official AIMS value.",
        ),
        (
            "SEMESTER",
            "No",
            "Text",
            "Batch-level semester when the file covers one term; preserve the official AIMS value exactly.",
        ),
        (
            "NOTES",
            "No",
            "Text",
            "Export-scope or correction notes. Do not include passwords or unnecessary sensitive data.",
        ),
    ],
    "Students": [
        (
            "STUDENT_NUMBER",
            "Yes",
            "Text",
            "AIMS-issued student number and authoritative identity key. Preserve leading zeroes.",
        ),
        ("LAST_NAME", "Yes", "Text", "Official last name from AIMS."),
        ("FIRST_NAME", "Yes", "Text", "Official first name from AIMS."),
        ("MIDDLE_NAME", "No", "Text", "Official middle name from AIMS, when available."),
        ("SUFFIX", "No", "Text", "Official name suffix from AIMS, when available."),
        (
            "INSTITUTIONAL_EMAIL",
            "No",
            "Text",
            "Official institutional email from AIMS, when available.",
        ),
        ("PROGRAM_CODE", "Yes", "Text", "Official program code from AIMS."),
        ("PROGRAM_NAME", "No", "Text", "Official program name from AIMS."),
        (
            "ADMISSION_STATUS",
            "No",
            "Text",
            "Externally maintained admission status, if included in the approved export.",
        ),
        (
            "ADMISSION_ACADEMIC_YEAR",
            "No",
            "Text",
            "Official admission academic year, if available.",
        ),
        (
            "ADMISSION_SEMESTER",
            "No",
            "Text",
            "Official admission semester, if available; preserve exact source formatting.",
        ),
        (
            "STUDENT_RECORD_STATUS",
            "Yes",
            "Text",
            "Official record status from AIMS. Do not translate into a locally invented status.",
        ),
        (
            "RECORD_LAST_UPDATED_AT",
            "No",
            "ISO 8601 datetime",
            "AIMS record update time when the source export provides it.",
        ),
        (
            "SOURCE_RECORD_ID",
            "No",
            "Text",
            "Stable AIMS source-record identifier when available.",
        ),
    ],
    "Enrollment_Subjects": [
        ("STUDENT_NUMBER", "Yes", "Text", "Must match a STUDENT_NUMBER in Students."),
        ("ACADEMIC_YEAR", "Yes", "Text", "Official academic year; preserve exact AIMS value."),
        ("SEMESTER", "Yes", "Text", "Official semester; preserve exact AIMS value."),
        ("SUBJECT_CODE", "Yes", "Text", "Official subject/course code."),
        ("SUBJECT_TITLE", "Yes", "Text", "Official subject/course title."),
        ("UNITS", "No", "Decimal", "Official units when available."),
        ("SECTION", "No", "Text", "Official section identifier when available."),
        (
            "ENROLLMENT_STATUS",
            "Yes",
            "Text",
            "Official AIMS enrollment status; remains read-only after import.",
        ),
        ("ENROLLED_AT", "No", "ISO 8601 datetime", "Official enrollment time when available."),
        (
            "STATUS_EFFECTIVE_AT",
            "No",
            "ISO 8601 datetime",
            "Effective time of the current official enrollment status when available.",
        ),
        (
            "RECORD_LAST_UPDATED_AT",
            "No",
            "ISO 8601 datetime",
            "AIMS record update time when available.",
        ),
        (
            "SOURCE_RECORD_ID",
            "No",
            "Text",
            "Stable AIMS enrollment-row identifier when available.",
        ),
    ],
    "Grades": [
        ("STUDENT_NUMBER", "Yes", "Text", "Must match a STUDENT_NUMBER in Students."),
        ("ACADEMIC_YEAR", "Yes", "Text", "Official academic year; preserve exact AIMS value."),
        ("SEMESTER", "Yes", "Text", "Official semester; preserve exact AIMS value."),
        ("SUBJECT_CODE", "Yes", "Text", "Official subject/course code."),
        ("SUBJECT_TITLE", "No", "Text", "Official subject/course title when supplied."),
        (
            "OFFICIAL_GRADE",
            "No",
            "Text",
            "Official grade exactly as exported by AIMS; never recalculate or translate locally.",
        ),
        (
            "COMPLETION_STATUS",
            "Yes",
            "Text",
            "Official completion/result status exactly as exported by AIMS.",
        ),
        (
            "GRADE_POSTED_AT",
            "No",
            "ISO 8601 datetime",
            "Official grade-posting time when supplied.",
        ),
        (
            "RECORD_LAST_UPDATED_AT",
            "No",
            "ISO 8601 datetime",
            "AIMS record update time when supplied.",
        ),
        (
            "SOURCE_RECORD_ID",
            "No",
            "Text",
            "Stable AIMS grade-row identifier when available.",
        ),
    ],
    "Subject_Offerings": [
        ("ACADEMIC_YEAR", "Yes", "Text", "Official academic year; preserve exact AIMS value."),
        ("SEMESTER", "Yes", "Text", "Official semester; preserve exact AIMS value."),
        ("PROGRAM_CODE", "Yes", "Text", "Program served by the offering."),
        ("SUBJECT_CODE", "Yes", "Text", "Official subject/course code."),
        ("SUBJECT_TITLE", "Yes", "Text", "Official subject/course title."),
        ("SECTION", "No", "Text", "Official section identifier when available."),
        (
            "FACULTY_IDENTIFIER",
            "No",
            "Text",
            "Official faculty identifier when authorized and available.",
        ),
        ("FACULTY_NAME", "No", "Text", "Official faculty display name when available."),
        ("SCHEDULE", "No", "Text", "Official schedule text when available."),
        (
            "OFFERING_STATUS",
            "No",
            "Text",
            "Official offering status when available.",
        ),
        (
            "RECORD_LAST_UPDATED_AT",
            "No",
            "ISO 8601 datetime",
            "AIMS record update time when supplied.",
        ),
        (
            "SOURCE_RECORD_ID",
            "No",
            "Text",
            "Stable AIMS offering-row identifier when available.",
        ),
    ],
}


def style_header(cell, required: bool = False) -> None:
    cell.font = Font(color=WHITE, bold=True)
    cell.fill = PatternFill("solid", fgColor=GREEN if required else "5B6573")
    cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
    cell.border = Border(bottom=THIN_GRAY)
    cell.protection = Protection(locked=True)


def add_readme(workbook: Workbook) -> None:
    sheet = workbook.active
    sheet.title = "README"
    sheet.sheet_view.showGridLines = False
    sheet.column_dimensions["A"].width = 24
    sheet.column_dimensions["B"].width = 105

    sheet.merge_cells("A1:B1")
    title = sheet["A1"]
    title.value = "PROPOSED USLS AIMS EXPORT / IMPORT TEMPLATE"
    title.font = Font(size=16, bold=True, color=WHITE)
    title.fill = PatternFill("solid", fgColor=GREEN)
    title.alignment = Alignment(horizontal="center", vertical="center")
    sheet.row_dimensions[1].height = 30

    rows = [
        (
            "Status",
            "PROPOSED FOR AIMS/REGISTRAR REVIEW — this is not an official current AIMS export format.",
        ),
        (
            "Purpose",
            "Defines the minimum file-based data requested by the Graduate School lifecycle application. AIMS remains external and authoritative.",
        ),
        (
            "Workflow",
            "Authorized AIMS export → validation and preview → atomic import → read-only display → discrepancy report → correction in AIMS → replacement export/import.",
        ),
        (
            "Important",
            "Do not add passwords, login credentials, birth dates, or unrelated personal data. Do not manually edit official values after export.",
        ),
        (
            "Schema version",
            SCHEMA_VERSION,
        ),
        (
            "Required sheets",
            "Export_Metadata, Students, Enrollment_Subjects, and Grades. Subject_Offerings is included for approval because the project also needs program, subject, faculty, and schedule data.",
        ),
        (
            "Date/time format",
            "ISO 8601 with time-zone offset, for example 2026-07-20T14:30:00+08:00.",
        ),
        (
            "Text handling",
            "Preserve AIMS codes, capitalization, leading zeroes, academic-year values, and semester values exactly. Do not use Excel formulas.",
        ),
        (
            "Official AIMS portal",
            OFFICIAL_PORTAL,
        ),
        (
            "Official AIMS guide",
            OFFICIAL_GUIDE,
        ),
        (
            "Source limitation",
            "The official portal and guide do not publish an API or export schema. Every field in this proposal requires confirmation by the authorized AIMS/Registrar owner.",
        ),
    ]

    for row_index, (label, value) in enumerate(rows, start=3):
        label_cell = sheet.cell(row=row_index, column=1, value=label)
        value_cell = sheet.cell(row=row_index, column=2, value=value)
        label_cell.font = Font(bold=True, color=GREEN)
        label_cell.fill = PatternFill("solid", fgColor=PALE_GREEN)
        value_cell.alignment = Alignment(wrap_text=True, vertical="top")
        label_cell.alignment = Alignment(wrap_text=True, vertical="top")
        label_cell.border = Border(bottom=THIN_GRAY)
        value_cell.border = Border(bottom=THIN_GRAY)
        sheet.row_dimensions[row_index].height = 35 if row_index in {3, 4, 5, 8, 13} else 25

    sheet["B11"].hyperlink = OFFICIAL_PORTAL
    sheet["B11"].style = "Hyperlink"
    sheet["B12"].hyperlink = OFFICIAL_GUIDE
    sheet["B12"].style = "Hyperlink"


def add_data_sheet(workbook: Workbook, name: str, fields: list[tuple[str, str, str, str]]) -> None:
    sheet = workbook.create_sheet(name)
    sheet.freeze_panes = "A2"
    sheet.auto_filter.ref = f"A1:{get_column_letter(len(fields))}1"
    sheet.sheet_view.showGridLines = False
    sheet.row_dimensions[1].height = 42

    for column_index, (field, required, data_type, description) in enumerate(fields, start=1):
        cell = sheet.cell(row=1, column=column_index, value=field)
        style_header(cell, required == "Yes")
        cell.comment = Comment(
            f"{'Required' if required == 'Yes' else 'Optional'} · {data_type}\n{description}",
            "CAPSTONE-USLS-MVP",
        )
        width = max(15, min(28, len(field) + 4))
        sheet.column_dimensions[get_column_letter(column_index)].width = width

    sheet.sheet_properties.pageSetUpPr.fitToPage = True
    sheet.page_setup.fitToWidth = 1
    sheet.page_setup.fitToHeight = 0
    sheet.auto_filter.ref = f"A1:{get_column_letter(len(fields))}1"

    # Keep the template empty. The importer treats row 2 onward as source data.
    for row_index in range(2, 102):
        for column_index in range(1, len(fields) + 1):
            cell = sheet.cell(row=row_index, column=column_index)
            cell.number_format = "@"
            cell.fill = PatternFill(
                "solid",
                fgColor=PALE_YELLOW if fields[column_index - 1][1] == "Yes" else WHITE,
            )

    sheet.protection.sheet = False


def add_data_dictionary(workbook: Workbook) -> None:
    sheet = workbook.create_sheet("Data_Dictionary")
    sheet.sheet_view.showGridLines = False
    headers = ["SHEET", "COLUMN", "REQUIRED", "TYPE / FORMAT", "RULE / DESCRIPTION"]
    widths = [24, 30, 12, 24, 100]
    for column_index, (header, width) in enumerate(zip(headers, widths), start=1):
        cell = sheet.cell(row=1, column=column_index, value=header)
        style_header(cell, True)
        sheet.column_dimensions[get_column_letter(column_index)].width = width

    row_index = 2
    for sheet_name, fields in SHEETS.items():
        for field, required, data_type, description in fields:
            values = [sheet_name, field, required, data_type, description]
            for column_index, value in enumerate(values, start=1):
                cell = sheet.cell(row=row_index, column=column_index, value=value)
                cell.alignment = Alignment(vertical="top", wrap_text=True)
                cell.border = Border(bottom=THIN_GRAY)
                if required == "Yes":
                    cell.fill = PatternFill("solid", fgColor=PALE_YELLOW)
            row_index += 1

    sheet.freeze_panes = "A2"
    sheet.auto_filter.ref = f"A1:E{row_index - 1}"
    sheet.row_dimensions[1].height = 30

    note_row = row_index + 1
    sheet.merge_cells(start_row=note_row, start_column=1, end_row=note_row, end_column=5)
    note = sheet.cell(row=note_row, column=1)
    note.value = (
        "Approval note: field availability, value codes, formats, export ownership, and cadence "
        "must be confirmed by the authorized AIMS/Registrar owner before production use."
    )
    note.font = Font(bold=True, color=RED)
    note.fill = PatternFill("solid", fgColor=PALE_BLUE)
    note.alignment = Alignment(wrap_text=True)
    sheet.row_dimensions[note_row].height = 35


def generate() -> Path:
    workbook = Workbook()
    add_readme(workbook)
    for name, fields in SHEETS.items():
        add_data_sheet(workbook, name, fields)
    add_data_dictionary(workbook)

    workbook.calculation.fullCalcOnLoad = True
    workbook.calculation.forceFullCalc = True
    workbook.properties.creator = "CAPSTONE-USLS-MVP"
    workbook.properties.title = "Proposed USLS AIMS Export / Import Template"
    workbook.properties.subject = "External AIMS file integration proposal"
    workbook.properties.description = (
        "Proposed, non-official workbook schema for stakeholder and AIMS/Registrar review."
    )

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    workbook.save(OUTPUT_PATH)
    return OUTPUT_PATH


if __name__ == "__main__":
    print(generate())
