"""Process chapters 4.1 to 4.5: admission, enrollment, course offering, withdrawal, dropping."""

from __future__ import annotations

from .common import (C, GN, H, HB, N, OFFICIAL, P, PRACTICE, PROPOSED, Process, R)

NS = "—"

ADMISSION = Process(
    num="4.1", key="ADM",
    title="Admission handoff and onboarding",
    purpose="To record that an applicant has been admitted through the University's admission process and to open the student's Graduate School monitoring record. Admission itself (entrance examination, interview, admission requirements, student number) belongs to the admission offices and the Registrar; the Graduate School receives the result.",
    who=["Applicant / student", "Admissions and Scholarship Administration Office (ASAO) and Guidance and Evaluation Center (GEC) (external)", "University Registrar (external)", "Graduate School Dean", "Academic Coordinator", "GS staff"],
    trigger="The applicant has passed the entrance examination and interview and has uploaded the admission requirements, and the Registrar has created the student record.",
    preconditions=["The applicant has completed the admission requirements listed in rule ADM-01.", "The student number and institutional email exist in the Registrar's record; the Graduate School does not create them (ADM-09)."],
    steps=[
        ("Applicant", "Sends a letter of intent, stating the program and attaching the transcript of records, to the admission office email, and waits for notification.", "Letter of intent; transcript of records", "Notification within 3-5 working days"),
        ("Applicant", "Creates an AIMS applicant account, pays the entrance examination fee and the admission fee, and uploads the receipts.", "AIMS account; official receipts", NS),
        ("GEC", "Sends the examination schedule and link; entrance examination results go to the respective professional school offices; the Graduate School schedules the interview.", "Examination result", NS),
        ("Applicant", "Attends the interview, then uploads the admission requirements in the online account; the recommender sends the Graduate School recommendation form to the Graduate School admission email.", "Admission requirements; Recommendation Form; Essay Questionnaire; Signed Undertaking Form", NS),
        ("Graduate School Dean", "On admission, gives the student information about the program of study. Students who did not meet the admission test cut-off are assigned a volunteer faculty adviser.", "Program of study", NS),
        ("Registrar", "Creates the student record and sends the admission or enrollment information to the Graduate School (in the format of the monitoring workbook).", "Monitoring workbook / file", "Before the term starts (during the term break)"),
        ("GS staff", "Records the handoff (source and date received) and opens the student's monitoring record by importing the file. GS staff do not create students one by one.", "Monitoring record", NS),
        ("Academic Coordinator", "Confirms that the program assignment is correct, or asks for a correction.", "Program confirmation", NS),
        ("GS staff / Dean", "Records onboarding as complete and reports it to the Dean, who acknowledges it.", "Onboarding status record", NS),
    ],
    rules=[
        R("ADM-01", "A student seeking admission must submit an accomplished admission application form, two letters of recommendation, one 2x2 ID picture, transcript of record, honorable dismissal or transfer credential, pass the entrance examination and interview, comply with program-specific requirements, and sign an undertaking to finish the bridging course in a year.", H("pp. 42-43"), OFFICIAL),
        R("ADM-02", "The entrance examination fee (Graduate School P400) and the admission fee (P300) are non-refundable.", H("p. 46"), OFFICIAL),
        R("ADM-03", "An applicant with insufficient background must take prerequisite or bridging courses; an applicant with a non-thesis master's degree enrolls in six units of thesis as a bridging course. The number of units differs by college.", H("pp. 43-44"), OFFICIAL),
        R("ADM-04", "A transferee may be credited a maximum of 25% of subjects taken during the last five years that are substantially the same in content, not credited to a previous degree, upon recommendation of the Admission Committee and within the residence requirement.", H("p. 45"), OFFICIAL),
        R("ADM-05", "A special student (audit only) needs the permission of the Dean and a signed agreement waiving the right to receive or demand credit.", H("p. 45"), OFFICIAL),
        R("ADM-06", "A foreign student pays an additional annual foreign fee; missionaries and religious, children of Overseas Filipino workers, special exchange students and students on audit are exempt.", H("p. 45"), OFFICIAL),
        R("ADM-07", "Upon admission the Dean gives the student information about the program of study; students who do not meet the admission test cut-off are assigned a volunteer faculty adviser.", H("p. 42"), OFFICIAL),
        R("ADM-08", "The applicant sends a letter of intent with the transcript of records and waits for notification within 3-5 working days before taking the entrance examination.", H("p. 45"), OFFICIAL),
        R("ADM-09", "The student number and the institutional email are created by the Registrar; the Graduate School does not generate or manually assign them.", [C("15 July 2026", "student number created by the Registrar"), N("July 20 checklist, items 3 and 4")], PRACTICE),
        R("ADM-10", "The admission checklist follows the official USLS admission process. The Graduate School does not repeat it; it records that admission was completed.", N("July 20 checklist, item 4 (stakeholder-confirmed answer)"), PRACTICE),
        R("ADM-11", "Student records enter the Graduate School's record through the monitoring workbook prepared from the official records (AIMS); GS staff do not create student records manually, and a missing student is checked against the official source.", [N("July 20 checklist, items 2 and 6 (stakeholder-confirmed answer)"), C("21 July 2026", "no AIMS integration")], PRACTICE),
        R("ADM-12", "GS staff record the source and the date of each handoff; the Academic Coordinator confirms the program assignment; the Dean acknowledges completed onboarding.", N("BPM accurate flow, section 1"), PROPOSED),
        R("ADM-13", "A possible duplicate student is identified by the student number, never by name alone; staff compare the records and confirm or merge them only when verified.", N("July 20 checklist, items 13 and 14"), PROPOSED),
    ],
    exceptions=[
        "The file is incomplete or a column is blank: the row is held and GS staff ask for a corrected file; the incomplete row is not entered (Proposed; Consultation 20 July 2026 discussion).",
        "A student is admitted late, after the file was sent: the Registrar sends an updated file; existing students are updated, new students are added (Consultation 20 July 2026 discussion).",
        "The Graduate School record and the official record disagree (for example a misspelled name): the official record is followed, the change is shown to the user, and the difference is flagged for follow-up (Proposed; Consultation 20 July 2026).",
        "A foreign student must submit additional authenticated requirements (grade interpretation, course syllabus, recommendation in narrative form, passport, medical insurance) to the ASAO Director (Handbook 2022-2023, pp. 46-47).",
    ],
    records=[
        ("Monitoring record created from the handoff file", "GS staff; the student monitoring workbook"),
        ("Program confirmation and onboarding status", "GS staff; reported to the Dean"),
        ("Admission documents and receipts", "Admission offices and AIMS (not kept by the Graduate School)"),
    ],
    platform="GS staff import the monitoring workbook; the platform creates the student records and the enrolled subjects from it. It flags students found in the file but missing from the platform, and differences between the file and what the platform holds. It does not create a student number or an email address.",
    platform_diff="The platform does not duplicate the admission checklist of the admission offices. The platform's onboarding checklist (admission approval, student profile sheet, program assignment, enrollment signal, official transcript) is the group's model and is not in any official source. Who imports the workbook (GS staff or the Academic Coordinator) is an open question (OQ-33).",
)

ENROLLMENT = Process(
    num="4.2", key="ENR",
    title="Enrollment and academic load",
    purpose="To state how a graduate student is advised and enrolled each semester and how many units a student may carry, and to state what the Graduate School records. Enrollment itself is done in AIMS through the Registrar and the Business Office.",
    who=["Student", "Academic Coordinator", "Business Office / Cashier (external)", "Registrar (external)", "GS staff"],
    trigger="The enrollment period opens (normally June to July) or a student returns for a new semester.",
    preconditions=["The student is admitted and has a student record.", "The subject offering for the term has been set (see 4.3).", "The student has no unsettled financial delinquency from the previous semester (ENR-04)."],
    steps=[
        ("Student", "Consults the Academic Coordinator for academic evaluation and electronic advising.", "Advising in AIMS", "Enrollment period (normally June to July)"),
        ("Academic Coordinator", "Studies the student's subjects taken and not taken and advises which offered subjects to take. Advises the subjects in AIMS and tags the student as enrolled in those subjects in the Graduate School's record.", "AIMS advising; subject status tag", "On the day of advising"),
        ("Student", "Pays at the Cashier in the Business Office.", "Official receipt", NS),
        ("Student", "Validates the enrollment in the AIMS account.", "AIMS validation", NS),
        ("Student", "Secures the ID sticker (continuing students) or ID (new students) from the Audio Visual Resource Center.", "ID sticker", NS),
        ("GS staff / Academic Coordinator", "Keeps the subject status current. A student who enrolls late is added to the class list by searching for the student and tagging the subject.", "Class list; subject status", "As students are advised"),
    ],
    rules=[
        R("ENR-01", "The enrolment procedures are: (1) academic evaluation and electronic advising with the Academic Coordinator, (2) payment at the Cashiers in the Business Office, (3) validation in the student's AIMS account, (4) ID issuance or renewal.", H("p. 47"), OFFICIAL),
        R("ENR-02", "The normal load of a part-time graduate student is six (6) to nine (9) units per semester, and twelve (12) units for a full-time student.", H("p. 48"), OFFICIAL),
        R("ENR-03", "Attendance is counted from the first regular class meeting regardless of the time of registration.", H("p. 52"), OFFICIAL),
        R("ENR-04", "Students with financial delinquencies at the close of the semester are not permitted to register in the succeeding semester unless previous accounts are settled.", H("p. 51"), OFFICIAL),
        R("ENR-05", "A master's student may transfer to another master's option with the approval of the Dean, upon the recommendation of the Academic Coordinator and endorsed by the Associate Dean.", H("p. 48"), OFFICIAL),
        R("ENR-06", "Coursework at another institution is credited only if the student secured the Dean's written permission in advance; the Registrar then issues a cross-enrollment permit. Cross-enrollment is normally allowed only to a graduating student for a course not offered in the graduating semester, and never for major elective or major professional courses.", H("p. 50"), OFFICIAL),
        R("ENR-07", "A special class may be requested by the Academic Coordinator through the Dean, addressed to the Vice Chancellor for Academic Affairs. An undersized class is treated as a special class.", H("p. 48"), OFFICIAL),
        R("ENR-08", "Enrollment takes place in AIMS. The Academic Coordinator advises the subjects and tags the student as enrolled in the Graduate School's record; the Graduate School record is a monitoring record.", C("21 July 2026"), PRACTICE),
        R("ENR-09", "There are no ordinary course-to-course prerequisites in the Graduate School; eligibility rules apply mainly to the comprehensive examination and to the thesis or dissertation stage.", N("July 20 checklist, items 16 and 75 (stakeholder-confirmed answer)"), PRACTICE),
        R("ENR-10", "Enrollment normally occurs in June to July. Dates are kept as configurable academic periods, not fixed dates.", N("July 20 checklist, items 10 and 76 (stakeholder-confirmed answer)"), PRACTICE),
        R("ENR-11", "Each student-subject pair has one status: not taken, enrolled, taken, dropped, withdrawn; and, as reported by faculty, incomplete or failed.", C("21 July 2026"), PRACTICE),
        R("ENR-12", "Faculty do not enter grades in the Graduate School record. A professor who fails a student or gives an incomplete reports it to the Academic Coordinator, who tags the status.", C("21 July 2026"), PRACTICE),
        R("ENR-13", "If the load tagged for a student is outside six to nine units (part-time) or twelve units (full-time), the platform shows a warning to the Academic Coordinator. The warning does not block the tag.", H("p. 48"), PROPOSED),
    ],
    exceptions=[
        "A student enrolls late or in a special class: the student is added to the class list of the subject by GS staff or the Academic Coordinator (Consultation 21 July 2026).",
        "A student who is not enrolled in any subject but wants to complete an INC, take the comprehensive examination, or wait for a research publication must enroll for residency (see 4.9).",
        "A student who does not intend to enroll for a valid reason such as medical reasons and still has remaining units files for a leave of absence, not residency (see 4.6).",
        "A student with a financial delinquency at the close of the semester may not register in the next semester until previous accounts are settled (ENR-04).",
    ],
    records=[
        ("Subject status per student and subject (enrolled)", "Monitoring workbook and platform record"),
        ("Class list per subject offering", "Academic Coordinator and GS staff"),
        ("Official enrollment and receipts", "AIMS and the Business Office"),
    ],
    platform="The platform shows each student's subjects and statuses, lets the Academic Coordinator or GS staff tag a subject as enrolled (by search or class-list upload), and shows the enrolled list per subject. It does not perform the official enrollment.",
    platform_diff="The platform accepts a unit range of 0 to 12 and does not check the six to nine unit normal load (ENR-13 is proposed). It does not check that a financial delinquency has been settled (ENR-04), because that belongs to the Business Office.",
)

OFFERING = Process(
    num="4.3", key="CRS",
    title="Course offering and course adjustments (change and add of subject)",
    purpose="To decide which subjects will be offered in a coming semester, to assign faculty and schedules, and to state when a student may change or add a subject after enrolling.",
    who=["Academic Coordinator", "Graduate School Dean", "Associate Dean", "GS staff", "Business Office (external)", "Student"],
    trigger="The semester is ending or has ended (term break) and the office must plan the next semester; or a student asks to change or add a subject in the first week of classes.",
    preconditions=["Current subject statuses are recorded (who has taken which subject).", "The monitoring record shows, for each program, which required subjects the students have not yet taken."],
    steps=[
        ("Academic Coordinator", "Reviews the consolidated list of students and subjects (taken and not taken) and the count of students who still need each subject (the subject needs report).", "Subject needs report; monitoring workbook", "During the term break, before enrollment"),
        ("Academic Coordinator", "Decides which subjects will be offered, and assigns the professor and schedule for each. Subjects with too few students may be left out or treated as a special class.", "Subject offering list (program, subject code, subject, faculty, schedule)", NS),
        ("Dean", "Reviews and approves the offering plan, or asks for a revision. (Group's process model; not confirmed.)", "Approved offering list", NS),
        ("GS staff", "Publishes and records the final offering list; students are tagged as enrolled in the offered subjects during enrollment (see 4.2).", "Offering list", NS),
        ("Student", "To change a subject: within the first week of classes, if the original subject is dissolved, if there is a schedule conflict, or if the student failed the prerequisite subject.", "Request to the Academic Coordinator", "First week of classes"),
        ("Student", "To add a subject: obtains the written approval of the Associate Dean in the first week of classes.", "Associate Dean's written approval", "First week of classes"),
        ("Student", "Un-tags the enrollment form at the Business Office, obtains an Advice Slip from the Graduate School Office, and goes through the enrolment procedure again.", "Advice Slip", "First week of classes"),
    ],
    rules=[
        R("CRS-01", "Changing one subject for another is allowed during the first week of classes if the original subject is dissolved, if the student has a schedule conflict, or if the student fails the prerequisite subject.", H("pp. 48-49"), OFFICIAL),
        R("CRS-02", "Adding subjects is allowed during the first week of classes upon the written approval of the Associate Dean.", H("p. 49"), OFFICIAL),
        R("CRS-03", "To add a subject: (1) un-tag the enrolment form in the Business Office, (2) secure an Advice Slip from the Graduate School Office, (3) go through the enrolment procedure.", H("p. 49"), OFFICIAL),
        R("CRS-04", "An undersized class is treated as a special class; the Graduate School Dean ensures that each new batch reaches the minimum number of enrollees to allow for attrition.", H("p. 48"), OFFICIAL),
        R("CRS-05", "A full refund is made to students for any courses discontinued by the school.", H("p. 51"), OFFICIAL),
        R("CRS-06", "Course adjustments (change and add) may continue until the first week of classes.", N("July 20 checklist, items 10, 34 and 77 (stakeholder-confirmed answer)"), PRACTICE),
        R("CRS-07", "The Academic Coordinator chooses the subjects to offer by studying which subjects students have and have not taken; each offering states the subject, the schedule and the professor; the Academic Coordinator decides who teaches it.", C("21 July 2026"), PRACTICE),
        R("CRS-08", "A subject counts as needed when at least one student needs it. A need is not an offering: subject need, proposed offering, approved offering and scheduled class are kept separate.", [N("July 20 checklist, items 31 and 85 (answer attributed to the Associate Dean)"), C("29 July 2026", "the group reports the demand cutoff of one as the Associate Dean's answer")], PRACTICE),
        R("CRS-09", "Offerings are planned during the term break, after the previous semester ends and before enrollment.", N("July 20 checklist, item 34; Consultation 29 July 2026 rehearsal"), PROPOSED),
        R("CRS-10", "The Dean approves the offering plan before it is published.", N("BPM accurate flow, section 3"), PROPOSED),
        R("CRS-11", "When the Academic Coordinator decides not to offer a subject, the platform shows which students would be delayed, so that the decision can be made with that information; the decision stays with the Academic Coordinator.", N("July 20 checklist, items 32, 33 and 86"), PROPOSED),
        R("CRS-12", "When assigning a professor the Academic Coordinator considers the professor's preferred subjects, availability, qualifications, current load and schedule conflicts; the platform only suggests.", N("July 20 checklist, items 36-40, 88-90"), PROPOSED),
    ],
    exceptions=[
        "A subject is not offered because demand is too low: affected students are advised to take another subject or wait; a special class may be requested through the Dean to the Vice Chancellor for Academic Affairs (Handbook 2022-2023, p. 48).",
        "Two subjects assigned to the same professor at the same time: the Academic Coordinator changes the professor or the schedule before the offering is confirmed (Consultation 29 July 2026 rehearsal; Proposed).",
        "A student enrolls late or in an unusual case outside the normal flow: the Registrar sends a list and the student is added to the class list (Consultation 29 July 2026; process not fully described in the sources).",
    ],
    records=[
        ("Subject needs report and offering decisions", "Academic Coordinator; Dean"),
        ("Published subject offering list", "GS staff; used for enrollment"),
        ("Advice Slip and written approval for added subjects", "GS Office and Associate Dean"),
    ],
    platform="The platform computes the subject needs from the curriculum and the subjects each student has taken, lets the Academic Coordinator choose what to offer and what to exclude, sends the plan to the Dean, publishes the approved offerings, and lets the Academic Coordinator assign a professor and a schedule. A class list can be uploaded or students tagged one at a time.",
    platform_diff="The platform has no change-of-subject or add-of-subject step with the first-week window, the conditions in CRS-01, or the Associate Dean's written approval (CRS-02). It suggests subjects for offering when one student needs them (CRS-08), which is how the Associate Dean described the need, but it does not test minimum class size (CRS-04); whether a subject with one student should be opened is an open question (OQ-34).",
)

WITHDRAWAL = Process(
    num="4.4", key="WD",
    title="Withdrawal of subject",
    purpose="To state when and how a student may withdraw from one subject, what the student pays, and what the Graduate School records. This chapter answers the panel's question on whether a student can drop at any time, including the first day.",
    who=["Student", "Graduate School Dean", "GS staff", "Registrar (external)", "Accounting Office and Business Office (external)"],
    trigger="A student who is enrolled in a subject decides not to continue with it (for example for work reasons) and writes to the Dean.",
    preconditions=["The student is enrolled in the subject.", "For a withdrawal at the lowest charge: no more than one week of classes has passed."],
    steps=[
        ("Student", "Writes a letter to the Dean asking to withdraw the named subject and giving the reason.", "Letter to the Dean", "Until the second week from the start of classes (see the timeline below)"),
        ("Dean", "Approves or denies the request. (The Handbook says the student seeks approval from the Dean.)", "Dean's decision", NS),
        ("Student", "Once approved, accomplishes the Withdrawal Form and settles all financial obligations.", "Withdrawal Form", NS),
        ("Graduate School", "Gives a copy of the accomplished Withdrawal Form to the Registrar, to the Accounting Office, and to the student.", "Withdrawal Form copies (3)", NS),
        ("GS staff", "Tags the subject as withdrawn in the Graduate School's record with the date applied, the date granted and a note.", "Subject status: withdrawn", "After the Dean's approval"),
        ("Registrar", "Processes the withdrawal in the registration system; the Business Office then arranges any tuition adjustment. The Graduate School's part ends when the request has been sent to the Registrar.", "Registrar processing (external)", NS),
    ],
    rules=[
        R("WD-01", "The student may withdraw subjects until the second week from the start of classes regardless of whether or not classes have been attended.", H("p. 49"), OFFICIAL),
        R("WD-02", "Ten percent (10%) of the total amount due for the term is charged if the withdrawal is within the first week of classes, and twenty percent (20%) if within the second week, regardless of whether or not classes have been attended.", [H("p. 49"), H("p. 51")], OFFICIAL),
        R("WD-03", "The student retains the right to withdraw all subjects at any time of the semester after the second week but pays the full enrolment fees for the semester.", H("p. 49"), OFFICIAL),
        R("WD-04", "The student may be charged all school fees in full if withdrawal is made at any time after the second week of classes. If the withdrawal is due to a justifiable reason, the student is charged pertinent fees only up to and including the last month of attendance.", H("p. 51"), OFFICIAL),
        R("WD-05", "A student may seek a refund if he or she withdraws during the first two weeks of classes when tuition and other fees have been paid in full, or for any length longer than one month.", H("pp. 50-51"), OFFICIAL),
        R("WD-06", "To file a withdrawal of subject, the student writes a letter and seeks approval from the Dean.", H("p. 49"), OFFICIAL),
        R("WD-07", "Once approved, the student accomplishes the Withdrawal Form and settles all financial obligations.", H("p. 49"), OFFICIAL),
        R("WD-08", "The accomplished Withdrawal Form is provided to the Registrar, the Accounting Office, and the student.", H("p. 49"), OFFICIAL),
        R("WD-09", "The grade symbol W means Withdrawn.", H("p. 53"), OFFICIAL),
        R("WD-10", "A subject withdrawal (from one subject, not from the Graduate School) before or in the first week of classes does not count against the student; dropping is the act of leaving a subject in the middle of the semester.", C("21 July 2026"), PRACTICE),
        R("WD-11", "An approved withdrawal is sent to the Registrar, which processes it in the registration system, and then to the Business Office for any fee arrangement. The Graduate School's responsibility ends at sending the request to the Registrar.", C("21 July 2026"), PRACTICE),
        R("WD-12", "After the Registrar has been sent the request, the Graduate School tags the subject as withdrawn (a manual tag is enough), with the date applied, the date granted and a text area for the result.", C("21 July 2026"), PRACTICE),
        R("WD-13", "According to the Associate Dean, a student may withdraw before classes begin or in the first week of classes; the Dean decides with discretion, and a request submitted after the deadline or with an insufficient or inconsistent justification is normally denied. (This is a second-hand account recorded by the group and conflicts with the Handbook's second week; see OQ-01.)", C("29 July 2026", "account of the Associate Dean's answer"), PRACTICE),
        R("WD-14", "The platform shows the student the Handbook's fee bracket for the date of the request (first week, second week, later) as information only; the Business Office computes the fee.", H("pp. 49, 51"), PROPOSED),
    ],
    exceptions=[
        "Withdrawal after the second week: the student may still withdraw but pays the full fees of the semester, unless the reason is justifiable, in which case fees are charged only up to the last month of attendance (WD-03, WD-04).",
        "Withdrawal from all subjects after two weeks have passed: the student files a leave of absence instead and pays the withdrawal fee at the Cashier's office (see 4.6).",
        "A course discontinued by the school: the student receives a full refund (CRS-05).",
        "The Dean denies the request: the subject stays enrolled and the student's record is unchanged. (The Handbook says the student seeks the Dean's approval but names no reasons for denial; the reasons in WD-13 are an account of the Associate Dean's answer. See OQ-04.)",
        "The Withdrawal Form: the Handbook names it but the blank form was not available to the group, so the form's fields are not described here.",
    ],
    records=[
        ("Student's letter and the Dean's decision", "Dean's office; GS staff"),
        ("Withdrawal Form (three copies)", "Registrar, Accounting Office, student"),
        ("Subject status: withdrawn, with date applied, date granted and notes", "Graduate School record; export to the Registrar"),
    ],
    platform="The student files a structured withdrawal request for one selected subject; GS staff forward it to the Dean; if approved, GS staff tag only that subject as withdrawn and prepare the list of approved withdrawals as an Excel file to be sent to the Registrar manually. The student stays active and the other subjects are unchanged. A denial leaves the enrollment unchanged.",
    platform_diff="The platform accepts a withdrawal only before classes begin or in the first seven calendar days of class and states that no academic penalty applies. The Handbook allows withdrawal until the second week, charges 10% in the first week and 20% in the second, and lets a student withdraw later by paying full fees. The platform's seven-day rule follows the group's account of the consultation (WD-13), not the Handbook. The Handbook is in force; the difference is listed as OQ-01.",
    callout="Panel question: can a student drop a subject at any time, for example on Day 1? Answer from the Handbook (2022-2023, pp. 49-53): Yes. Day 1 is inside the first week, so a student may withdraw a subject on Day 1 with the Dean's approval, but it is not free: 10% of the total amount due for the term is charged in the first week and 20% in the second week. A student may also change a subject or add a subject only in the first week. After the second week the student may still withdraw but pays the full fees (or fees up to the last month of attendance if the reason is justifiable). A student who is absent for more than 20% of the class hours in a course is dropped automatically by the professor with the grade DRP (see 4.5). What the Handbook does not say is what a withdrawal before the first day of classes costs (OQ-02), and what a withdrawal after the second week is called and marked (OQ-03).",
    extras=[
        {"title": "Timeline of consequences (Handbook 2022-2023, pp. 49-53)", "header": ["When", "What the student may do", "Fee consequence", "Source"], "rows": [
            ["Before classes begin", "The Handbook does not state a rule. (Consultation: withdrawal is possible before classes begin.)", "Not stated (OQ-02)", "Handbook silent; Consultation 29 July 2026"],
            ["First week of classes, including Day 1", "Withdraw a subject with the Dean's approval. Change a subject (three conditions). Add a subject with the Associate Dean's written approval.", "10% of the total amount due for the term", "Handbook 2022-2023, pp. 48-49, 51"],
            ["Second week of classes", "Withdraw a subject. Changing and adding are no longer allowed.", "20% of the total amount due for the term", "Handbook 2022-2023, pp. 49, 51"],
            ["After the second week", "The student keeps the right to withdraw all subjects at any time, and may file a leave of absence.", "Full enrolment fees for the semester (only up to the last month of attendance if the reason is justifiable)", "Handbook 2022-2023, pp. 49, 51"],
            ["Any time, for absences", "If unexcused absences exceed 20% of the class hours in a course, the professor drops the student automatically (grade DRP, 5.0).", "Not stated", "Handbook 2022-2023, p. 52"],
        ]},
    ],
)

DROPPING = Process(
    num="4.5", key="DRP",
    title="Dropping, including being dropped for absences",
    purpose="To state how a subject is dropped, whether by the professor for excessive absences or at the student's request during the semester, and how the Graduate School records it.",
    who=["Student", "Professor", "Academic Coordinator", "GS staff", "Registrar (external)"],
    trigger="Either the student's unexcused absences in a course exceed 20% of the scheduled hours, or a student in the middle of the semester decides to drop a subject.",
    preconditions=["The student is enrolled in the subject.", "For a request after the second week of classes, see 4.4 for the alternative (withdrawal with full fees)."],
    steps=[
        ("Professor", "Counts attendance from the first regular class meeting. When unexcused absence exceeds 20% of the hours of recitation, lecture, laboratory or other scheduled work in a course, drops the student from the course.", "Attendance record; grade DRP (5.0)", "Automatic when the 20% limit is exceeded"),
        ("Student (voluntary drop)", "Tells the Academic Coordinator (in person or by email) that the student wishes to drop the subject. The request is made outside the platform.", "Email or conversation", NS),
        ("Academic Coordinator / GS staff", "Once the drop is agreed, tags the subject as dropped, with the date and a note, in the Graduate School's record.", "Subject status: dropped", NS),
        ("GS staff", "Drops the subject in AIMS as well, so that the Graduate School record and AIMS agree.", "AIMS record", NS),
        ("Registrar", "Holds the official record of the drop.", "Registrar's record (external)", NS),
    ],
    rules=[
        R("DRP-01", "Students are expected to attend classes regularly; the maximum number of absences allowed a student is 20% of the total number of class hours for the whole semester.", H("p. 52"), OFFICIAL),
        R("DRP-02", "A student may be excused for a death in the family, illness (with a medical certificate from the USLS clinic or a personal doctor), or a graduate program activity endorsed by the Dean. Excuses are for time missed only, and all work missed must be made up to the satisfaction of the professor within a reasonable time.", H("p. 52"), OFFICIAL),
        R("DRP-03", "When unexcused absence reaches more than 20% of the stipulated hours in one course, the student is automatically dropped from the course by the professor and is given a grade of DRP with a 5.0 grade.", H("p. 52"), OFFICIAL),
        R("DRP-04", "A student who takes part in a school-sponsored activity or represents the University in an official capacity is granted an Approved Absence on the Dean's approval; it is not counted against the allowed absences.", H("p. 52"), OFFICIAL),
        R("DRP-05", "The grade symbols D (Dropped) and W (Withdrawn) appear in the grading system; students with grades INC, D or W, or who repeated a subject, are not eligible for the special academic honors.", H("pp. 53, 55"), OFFICIAL),
        R("DRP-06", "If a student gets a 5.0 he or she is automatically dropped from the program; failure in any subject means no re-admission to the program.", H("p. 54"), OFFICIAL),
        R("DRP-07", "A student drops a subject during the semester by talking or writing to the Academic Coordinator. Once agreed, the Academic Coordinator or GS staff tag the subject as dropped with a date and notes. No student-facing drop request is needed in the Graduate School's record.", C("21 July 2026"), PRACTICE),
        R("DRP-08", "The Graduate School drops the subject in AIMS as well as in its own record.", C("21 July 2026"), PRACTICE),
        R("DRP-09", "A drop requested by a student is recorded without a Graduate School approval step (there is no Deny). The status moves from requested to recorded and stays marked as awaiting confirmation until the Graduate School has seen the change in AIMS.", N("July 20 checklist, items 18, 19 and 79 (revision adopted after the 15 July adviser session)"), PROPOSED),
        R("DRP-10", "A request made up to the end of the second week of classes is handled as a withdrawal (see WD-01); a request made later is recorded as a drop. The Handbook does not give this dividing line; it is the group's reading of the Associate Dean's distinction between withdrawal and dropping.", [H("p. 49"), C("21 July 2026")], PROPOSED),
        R("DRP-11", "To remain in good standing a master's student must maintain a weighted average of 2.0 or better, and a doctorate student 1.75 or better, at the end of each academic year; a grade of 3.0 (master's) or 2.0 (doctorate) is passing but carries no graduate credit.", H("p. 54"), OFFICIAL),
        R("DRP-12", "A grade of INC may be given if the class standing is passing but the student fails to take the final examination or complete other requirements for illness or other valid reasons. It is removed within one academic year by meeting all course requirements and submitting the Incomplete Grade Removal Form to the Graduate School Office within the set deadline; after a year without compliance the grade becomes 3.0 (master's) or 2.0 (doctorate) and the subject is taken again; a student with INC in all subjects is dropped from the rolls of the Graduate School.", H("p. 54"), OFFICIAL),
    ],
    exceptions=[
        "Absence reaches more than 20% because of illness or death in the family: the excuse with a medical certificate or proof applies and the absence is not unexcused (DRP-02).",
        "A student drops a subject without telling anyone: the Graduate School learns of it only from the professor's report or from AIMS. The sources do not say how the Graduate School is informed (OQ-05).",
        "A student who stops enrolling without a leave of absence may be treated as absent without leave (see 4.8); the platform treats a full-semester withdrawal without an approved leave as AWOL evidence (Proposed).",
        "A drop that causes a student to fall behind the curriculum is a delayed case that the Academic Coordinator follows up (Proposed).",
    ],
    records=[
        ("Attendance record and DRP grade", "Professor; Registrar"),
        ("Subject status: dropped, date and notes", "Graduate School record"),
        ("AIMS drop", "Registrar / AIMS"),
    ],
    platform="GS staff or the Academic Coordinator tag a subject as dropped with a date and a note, as the Associate Dean described. The student can see the status on the enrolled-subject list. No drop form or supporting document is required.",
    platform_diff="The platform does not know about the 20% absence rule and does not produce the DRP grade; absences are kept by the professor. The platform does not distinguish a drop from a withdrawal by the date (DRP-10 is proposed). Whether a drop may be refused, what a drop costs, and whether a DRP 5.0 also ends the student's program are open questions (OQ-04 to OQ-06).",
    callout="Panel question: can a student drop a subject at any time, for example on Day 1? See the answer and the timeline in 4.4. In short: a Day 1 request is a withdrawal, allowed with the Dean's approval at a 10% charge; there is no rule in the Handbook that lets a student simply drop without a charge, and the Handbook's dropping rule is the automatic drop for absences.",
)
