"""Process chapters 4.11 to 4.16: title defense through scheduling."""

from __future__ import annotations

from .common import (C, H, N, OFFICIAL, P, PRACTICE, PROPOSED, Process, R)

NS = "—"
TITLE_FEES = "Fee tables are blank in the copy of the Protocol supplied; amounts are not known (OQ-27)."

TITLE = Process(
    num="4.11", key="TTL",
    title="Title defense",
    purpose="To have the student's three proposed research titles deliberated by a panel, so that one title is approved for the project paper, thesis or dissertation.",
    who=["Student", "Academic Coordinator", "Research Coordinator (RC)", "GS Research Committee", "GS Office (scheduling)", "Panel chair and panel members"],
    trigger="The student is ready to propose a research title.",
    preconditions=["The student has three concept papers.", "The student applies at least two weeks before the defense (TTL-01).", "Platform only: the comprehensive examination has been passed (see CEX-13 and OQ-17)."],
    steps=[
        ("Student", "Accomplishes Form 1, Application for Title Defense, and emails Form 1 and the three concept papers to the Academic Coordinator.", "Form 1; 3 concept papers", "At least 2 weeks before the scheduled defense"),
        ("Academic Coordinator", "Endorses Form 1 and the three concept papers to the Research Coordinator at the GS mailbox by e-signature (instead of signing Form 1), and recommends a set of panel members.", "Form 1 with AC e-signature", NS),
        ("Research Coordinator", "Nominates the panel members as recommended by the Academic Coordinator, after deliberation with the GS Research Committee.", "Panel nomination", NS),
        ("GS Office", "Coordinates with the panel members about the proposed schedule of the title defense.", "Schedule", NS),
        ("Research Coordinator", "Informs the nominated panel members and the student of the date and time, and sends the three concept papers and Form 2 to the panel.", "Form 2 (blank); concept papers", NS),
        ("Panel chair", "Prepares and emails the online details (meeting ID and password, or meeting link) to panel and student before the defense, and hosts the defense.", "Meeting details", "Before the defense"),
        ("Panel", "Deliberates the three titles without the student. The chair then admits the student, who takes note of the comments. The chair may record the defense with everyone's consent.", "Comments", "At the defense"),
        ("Panel members", "Decide the title to be pursued; each accomplishes Form 2 with the result and other information.", "Form 2", "After the defense"),
        ("Panel chair", "Emails the accomplished Form 2 to the Research Coordinator and the student.", "Form 2", "Within the first working day after the defense"),
        ("Student", "If the titles were disapproved, presents a new set of three titles and repeats the protocol. Settles the defense fees with the panel and emails the screenshot or deposit slip to the GS mailbox with the subject LAST NAME_type of defense_receipt.", "New titles; payment proof", "Within the first working day after the defense"),
    ],
    rules=[
        R("TTL-01", "The application for title defense (Form 1 and three concept papers to the Academic Coordinator) must be made at least two weeks before the scheduled defense.", [H("p. 59"), P("Title Defense, Part I, step 2 note")], OFFICIAL),
        R("TTL-02", "The Research Coordinator nominates the panel members as recommended by the Academic Coordinator, after deliberation with the GS Research Committee.", [H("p. 60"), P("Title Defense, Part I, step 4")], OFFICIAL),
        R("TTL-03", "Panel for a project paper: one panel chair and two members (one content specialist and one method specialist). Thesis or bridging thesis: one chair and three members (one content specialist, one method specialist and one external panel). Dissertation: one chair and four members (two content specialists, one method specialist and one external panel). The chair and the content and method specialists are University-affiliated; the external panel is a content or industry expert who takes part from the proposal defense onwards.", [H("p. 60"), P("Title Defense, Part I, step 4")], OFFICIAL),
        R("TTL-04", "The panel members deliberate the three submitted titles without the presence of the student; the chair then admits the student.", [H("p. 60"), P("Title Defense, Part II")], OFFICIAL),
        R("TTL-05", "The panel chair may record the defense with the consent of everyone in the meeting room and furnish the student the link of the recording.", H("p. 60"), OFFICIAL),
        R("TTL-06", "The panel chair emails the accomplished Form 2 to the Research Coordinator and the student within the first working day after the defense.", [H("p. 61"), P("Title Defense, Part III, step 2")], OFFICIAL),
        R("TTL-07", "If the proposed titles are disapproved, the student presents a new set of three titles and follows the same protocol; the decision is reflected in Form 2.", [H("p. 61"), P("Title Defense, Part III, step 3")], OFFICIAL),
        R("TTL-08", "The student asks the panel about their preferred mode of payment, settles the title defense fees and emails the proof to the GS mailbox within the first working day after the defense, with the subject line LAST NAME_type of defense_receipt.", [H("p. 61"), P("Title Defense, Part III, step 4")], OFFICIAL),
        R("TTL-09", "Thesis or project paper writing must be finished within two years from the title or proposal defense; for the thesis the student has one year from the title defense to submit and defend a proposal. Dissertation writing must be finished within three years from the title defense, with one year to submit and defend a proposal.", H("p. 58"), OFFICIAL),
        R("TTL-10", "If the approved title is still applicable, the same concept paper may be presented for re-defense; otherwise the student changes the research title or topic and goes through the title defense again.", H("p. 58"), OFFICIAL),
        R("TTL-11", "GS staff check that Form 1, three concept papers and the Academic Coordinator's endorsement are present before the Research Coordinator nominates a panel. The check is for completeness only.", N("July 20 checklist, item 42; Group working notes, transactions list"), PROPOSED),
        R("TTL-12", "The platform does not schedule a title defense, nominate a panel or approve a title by itself; panel candidates are suggested from faculty specialization, availability and workload and staff may choose any faculty.", N("July 20 checklist, item 44"), PROPOSED),
    ],
    exceptions=[
        "All three titles disapproved: the student presents three new titles and repeats the process (TTL-07).",
        "Student wants to keep the approved title after a long delay: the same concept paper may be re-presented if still applicable (TTL-10).",
        "Student abroad: the defense is online; the chair sends the login details (Research Protocol, Proposal Defense, Part I, states this for the proposal defense; the title defense is held on the chosen platform).",
        "Panel members cannot agree on a title: the Protocol does not say what happens.",
        TITLE_FEES,
    ],
    records=[
        ("Form 1 and the three concept papers", "Research Coordinator; GS mailbox"),
        ("Form 2, Report of Title Defense (approved title)", "Research Coordinator; research monitoring workbook (approved title, schedule)"),
        ("Fee payment proof", "GS mailbox"),
    ],
    platform="The student submits Form 1 and the three concept papers in the platform; the Academic Coordinator endorses; the Research Coordinator selects the panel (the platform suggests candidates and staff may override); the schedule is confirmed (see 4.16); the panel chair records the result and the approved title.",
    platform_diff="The platform requires the comprehensive examination to be passed first (CEX-13), which the Protocol does not state. It allows a title defense to be confirmed with no lead time, whereas the Protocol asks for two weeks' notice (TTL-01). For a project paper the platform includes an external panel member, which the Protocol does not (TTL-03; OQ-42).",
)

ADVISER = Process(
    num="4.12", key="ADV",
    title="Adviser designation, advising contract, change of title and change of adviser",
    purpose="To appoint a research adviser for a student, to set the advising timetable and contract, and to handle the one allowed change of title and change of adviser.",
    who=["Student", "Academic Coordinator", "Research Coordinator (RC)", "Associate Dean", "Graduate School Dean", "Adviser and proposed adviser", "Panel chair and panel members (change of title)"],
    trigger="The student has an approved title or, earlier, wants an adviser while still taking courses.",
    preconditions=["The proposed adviser is a faculty of the University whose program is aligned with the student's program.", "The proposed adviser is within the advisee limit."],
    steps=[
        ("Student", "Accomplishes Form 3, Application for Designation of Research Adviser, and emails it to the Academic Coordinator.", "Form 3", NS),
        ("Academic Coordinator", "Writes an email or letter to the Research Coordinator at the GS mailbox \"noting\" the application. The Dean's e-signature is not required at this point.", "AC note", NS),
        ("Research Coordinator", "Emails Form 3 to the Dean for deliberation and appropriate action. Once the adviser is decided, the Research Coordinator, the Associate Dean and the Dean affix their e-signatures.", "Form 3 signed by RC, AD, Dean", NS),
        ("Research Coordinator", "Emails Form 3.1, Appointment for Research Adviser, to the student and the appointed adviser.", "Form 3.1", NS),
        ("Student / adviser", "Email back the accomplished Form 3.1 to the Research Coordinator.", "Form 3.1 (accomplished)", NS),
        ("Student and adviser", "Accomplish Form 3.2, Research Timetable, and Form 3.3, Thesis/Dissertation Advising Contract, and the student emails them to the Research Coordinator.", "Forms 3.2, 3.3", "Within 5 days of receipt of Form 3.1"),
        ("Student (change of title)", "Emails Form 3.4 and the new concept paper to the adviser, who endorses the request to the panel (copy to the RC). The panel deliberates and the chair emails the decision to the student, adviser and RC.", "Form 3.4; new concept paper", "Before the proposal defense application"),
        ("Student (change of adviser)", "Accomplishes Form 3.1.1 signed by the current and the new adviser and emails it to the Research Coordinator. The RC, Associate Dean and Dean deliberate; if approved, a new Form 3.1 is prepared.", "Form 3.1.1; new Form 3.1", "Before the proposal defense"),
    ],
    rules=[
        R("ADV-01", "The research adviser must be affiliated with the University and the degree program must be aligned with the student's program.", [H("p. 61"), P("Designation of the Research Adviser, Part I, step 1")], OFFICIAL),
        R("ADV-02", "Protocol: the research adviser must have a PhD degree for PhD students and at least PhD units for MA students (CHED CMO 15), and should have a maximum of five active advisees for the current academic year.", P("Designation of the Research Adviser, Part I, step 1 note"), OFFICIAL),
        R("ADV-03", "Handbook: the adviser shall be a faculty of the Graduate School and a holder of a doctoral degree aligned with the discipline, with at least one publication in a refereed journal or publicly recognized creative or technology outputs (CMO 15 s. 2019).", H("p. 58"), OFFICIAL),
        R("ADV-04", "In the exigency of service a faculty member may have more than five advisees with the approval of the Dean.", H("p. 58"), OFFICIAL),
        R("ADV-05", "The student may express a preference, but the Dean, the Associate Dean and the Research Coordinator make the final decision based on the degree, expertise, research work, number of advisees (maximum five per semester) and total workload of the faculty member.", H("p. 59"), OFFICIAL),
        R("ADV-06", "The choice of adviser gives primary importance to the student's choice with the approval of the program adviser and the Dean; the Dean appoints the adviser on the basis of expertise in the student's topic following the Research Protocol.", H("p. 58"), OFFICIAL),
        R("ADV-07", "Faculty of other universities may serve as adviser in some circumstances if they are adjunct faculty of the Graduate School.", H("p. 58"), OFFICIAL),
        R("ADV-08", "The assignment of an adviser may be done while the student is still taking academic courses.", H("p. 58"), OFFICIAL),
        R("ADV-09", "Form 3 is emailed by the student to the Academic Coordinator, who notes it to the Research Coordinator; the Dean's e-signature is not required at that point; the Research Coordinator emails Form 3 to the Dean; the Research Coordinator, the Associate Dean and the Dean sign; the Research Coordinator emails Form 3.1 to the student and adviser, who email the accomplished form back.", [H("p. 61"), P("Designation of the Research Adviser, Part I, steps 2-5")], OFFICIAL),
        R("ADV-10", "The advisee and adviser accomplish Form 3.2 and Form 3.3; the student emails them to the Research Coordinator within five days of receipt of Form 3.1.", [H("pp. 61-62"), P("Designation of the Research Adviser, Part II")], OFFICIAL),
        R("ADV-11", "The adviser is bound only to advising and shall not be selected as editor of the student or to any other appointment related to the conduct of the study.", H("p. 59"), OFFICIAL),
        R("ADV-12", "The adviser monitors the research according to the timetable in Form 3.2, reviews submitted proposals, questionnaires and chapters, gives technical and moral guidance, conducts a mock defense when necessary, attends the defense of the advisee, attends orientations set by the Graduate School, and adheres to the Research Protocol.", H("p. 59"), OFFICIAL),
        R("ADV-13", "A student may make only one request to change the title of the study, before the proposal defense application: Form 3.4 and the new concept paper go to the adviser, who endorses the request to the panel; the panel deliberates and the chair emails the decision.", [H("p. 62"), P("Change of Title of the Study")], OFFICIAL),
        R("ADV-14", "A student may make only one request to change the research adviser, before the proposal defense, for justifiable reasons: Form 3.1.1 signed by the current and new adviser, deliberated by the Research Coordinator, Associate Dean and Dean; then a new Form 3.1.", [H("p. 62"), P("Request for Change of Research Adviser")], OFFICIAL),
        R("ADV-15", "An adviser designated before the effectivity of his or her retirement may continue to serve until the final defense.", H("p. 58"), OFFICIAL),
        R("ADV-16", "The student needs to propose three faculty as adviser options.", C("21 July 2026", "Associate Dean's description"), PRACTICE),
        R("ADV-17", "Each nominated faculty member may accept or decline the nomination in the platform (the Associate Dean suggested this); the student and the Graduate School then choose among those who accept.", C("21 July 2026", "Associate Dean's suggestion"), PROPOSED),
        R("ADV-18", "Adviser-dependent steps (adviser signature, endorsement, document review, availability in scheduling) are blocked until an adviser is designated.", N("July 20 checklist, item 43"), PROPOSED),
    ],
    exceptions=[
        "The proposed adviser is over the advisee limit: the Dean may approve more than five in the exigency of service (ADV-04); the Handbook says five per semester and the Protocol five active advisees per academic year (OQ-20).",
        "The student wants a second change of title or adviser: the Protocol allows only one of each and only before the proposal defense (ADV-13, ADV-14).",
        "The adviser is unavailable or leaves the University: not stated in the sources, apart from retirement (ADV-15).",
    ],
    records=[
        ("Forms 3 and 3.1 with e-signatures", "Research Coordinator; research monitoring workbook (research adviser)"),
        ("Forms 3.2 and 3.3", "Research Coordinator"),
        ("Forms 3.4 and 3.1.1 and the decisions", "Research Coordinator"),
    ],
    platform="The student nominates advisers and submits Form 3; the Research Coordinator forwards it to the Dean; the Dean, the Associate Dean and the Research Coordinator sign; Form 3.1 is sent and the adviser is recorded. The platform blocks adviser-dependent steps without an adviser.",
    platform_diff="Who finally approves an adviser differs between the Handbook and the Protocol, and so do the adviser's qualifications and the advisee limit (OQ-19, OQ-20). The platform does not count the adviser's active advisees or check CMO 15 qualifications. The three-nominee practice (ADV-16) is not in the Handbook or the Protocol (OQ-21).",
)

PROPOSAL = Process(
    num="4.13", key="PRP",
    title="Proposal defense and ethics review",
    purpose="To have the student's research proposal examined by a panel and, after revisions, to obtain the technical review certificate and ethics clearance that precede the final defense.",
    who=["Student", "Statistician", "Research adviser", "Research Coordinator", "GS Research Committee", "Panel chair and panel members (including the external panel)", "Research ethics office", "GS Office"],
    trigger="The student has an adviser and a proposal paper that complies with the Graduate School's research paper guidelines.",
    preconditions=["One year from the title defense has not passed (TTL-09).", "The student has consulted a statistician (quantitative studies).", "An adviser is designated (ADV-18)."],
    steps=[
        ("Student", "Consults a statistician (quantitative studies) and obtains the accomplished Form 4.1, Statistical Consultation Form. Form 4.1 is not required for qualitative studies.", "Form 4.1", "Before the proposal defense"),
        ("Student", "Emails the adviser the proposal paper and Form 4.1.", "Proposal paper; Form 4.1", NS),
        ("Research adviser", "Reviews the manuscript and, once it complies with the Graduate School's research paper guidelines, accomplishes Form 4, Endorsement for Proposal/Final Defense, with e-signature.", "Form 4", "At least 2 weeks before the date of the defense"),
        ("Student (optional)", "Submits Form 4.2, Co-authorship Information for Publication, if the student will have a co-author.", "Form 4.2", NS),
        ("Research adviser", "Recommends the preferred external panel, whose expertise is aligned with the student's. The recommendation is subject to the approval of the GS Research Committee (Protocol) or the GS office (Handbook).", "Recommendation", NS),
        ("Student and adviser", "Agree with the panel members on the date and time, indicate the agreed schedule in Form 4, and give the panel the manuscript and Form 4.1.", "Form 4 (schedule)", "Panel has two weeks to review before the defense"),
        ("Research adviser", "Emails Form 4, the proposal paper and Form 4.1 to the Research Coordinator.", "Form 4", NS),
        ("Research Coordinator", "Emails the manuscript, Form 4.1 and Form 5, Comments Sheet for Proposal Defense, to the panel, adviser and student.", "Form 5 (blank)", NS),
        ("Panel chair", "Coordinates with the GS Office for the venue (or prepares online details, including for students abroad) and tells student, adviser and panel.", "Venue or online details", "Before the defense"),
        ("Panel", "Deliberates first without student and adviser; then the chair admits both. Before the presentation, the chair asks whether the student has a study grant and a plan for a co-author. The adviser records the comments. After the presentation and questions, the panel deliberates and announces the result. If major revisions are recommended, a re-defense is advised.", "Form 5", "At the defense"),
        ("Each panel member / panel chair", "Each member accomplishes Form 5 and emails it to the chair; the chair emails the consolidated Form 5 to the student, adviser and Research Coordinator.", "Consolidated Form 5", "Within the first working day after the defense"),
        ("Student / adviser / panel", "The student revises; the adviser endorses the revised manuscript and Form 5 to the panel for approval and the release of Form 5.1, Technical Review Certificate; the chair emails Form 5.1 to the student and adviser with copy to the Research Coordinator.", "Form 5.1", NS),
        ("Student", "Accomplishes Form 5.2, Application for Ethics Review, and emails it with the revised manuscript and Form 5.1 to the research ethics office.", "Form 5.2", "Within one month after the proposal defense"),
        ("Student", "Settles the panel fees and emails the proof to the GS mailbox.", "Payment proof", "Within the first working day after the defense"),
    ],
    rules=[
        R("PRP-01", "Before the proposal defense the student must have consulted a statistician for a quantitative study, with Form 4.1 accomplished by the statistician. Form 4.1 is not required for qualitative studies.", [H("p. 63"), P("Proposal Defense, Part I (statistical consultation)")], OFFICIAL),
        R("PRP-02", "The research adviser accomplishes Form 4 with e-signature once the paper complies with the research paper guidelines set by the Graduate School Office; this must be done at least two weeks before the date of the defense.", [H("p. 63"), P("Proposal Defense, Part I (Form 4 endorsement and note)")], OFFICIAL),
        R("PRP-03", "The panel members are given two weeks to review the paper before the scheduled proposal defense.", [H("p. 63"), P("Proposal Defense, Part I (panel review period)")], OFFICIAL),
        R("PRP-04", "The adviser's recommendation of an external panel is subject to the approval of the GS Research Committee (Dean, Associate Dean, Academic Coordinator, Research Coordinator) according to the Protocol, and to the approval of the GS office according to the Handbook.", [H("p. 63"), P("Proposal Defense, Part I (external panel recommendation)")], OFFICIAL),
        R("PRP-05", "For co-authorship, the student must have the major part and contribute at least 80% during the conduct of the study and must adhere to the contribution of work in Form 4.2; co-authorship or study grant agreements follow the institutional guidelines of the Center for Research and Engagement.", [H("p. 64"), P("Proposal Defense, Part II (co-authorship note)")], OFFICIAL),
        R("PRP-06", "The panel deliberates the paper first without the student and the adviser; if major revisions are recommended the student is advised to do a re-defense following the same protocol, reflected in Form 5.", [H("p. 64"), P("Proposal Defense, Part II")], OFFICIAL),
        R("PRP-07", "The panel chair emails the consolidated Form 5 to the student, the adviser and the Research Coordinator within the first working day after the defense.", [H("p. 64"), P("Proposal Defense, Part III (consolidated Form 5)")], OFFICIAL),
        R("PRP-08", "The application for ethics review (Form 5.2 with the revised manuscript and Form 5.1) is made within one month after the proposal defense.", [H("p. 65"), P("Proposal Defense, Part III (ethics review note)")], OFFICIAL),
        R("PRP-09", "The student settles payment to the preferred method of the panel members and emails the proof to the GS mailbox within the first working day after the defense.", [H("p. 65"), P("Proposal Defense, Part III (payment)")], OFFICIAL),
        R("PRP-10", "A student who has used a change of title or a change of adviser must have done so before the proposal defense application (ADV-13, ADV-14).", H("p. 62"), OFFICIAL),
        R("PRP-11", "Ethics clearance is needed before the closed-door final defense: the adviser emails Form 4, the Ethics Clearance and the manuscript to the Research Coordinator.", [H("p. 65"), P("Closed-door Final Defense, Part I (Form 4 submission)")], OFFICIAL),
        R("PRP-12", "The Research Coordinator records ethics clearance as received; the office checks that the document is present, not its content.", N("July 20 checklist, item 42"), PROPOSED),
        R("PRP-13", "The platform blocks the proposal endorsement without an adviser, and, for quantitative studies, without Form 4.1.", N("July 20 checklist, item 43; Platform (current build)"), PROPOSED),
    ],
    exceptions=[
        "Major revisions: the student is advised to re-defend and follows the same protocol (PRP-06).",
        "Qualitative study: Form 4.1 is not required (PRP-01).",
        "Student abroad: the panel chair recommends an online deliberation and sends the login details (Research Protocol, Proposal Defense, Part I).",
        "The external panel member: from the proposal defense onward (TTL-03); approval route differs (OQ-22).",
        "Panel fee amounts are not known (OQ-27).",
    ],
    records=[
        ("Forms 4, 4.1, 4.2 and the manuscript", "Research Coordinator; research monitoring workbook (endorsement and schedule of proposal)"),
        ("Form 5, consolidated comments sheet", "Research Coordinator; student; adviser"),
        ("Form 5.1 Technical Review Certificate; Form 5.2; ethics clearance", "Research Coordinator; research ethics office; research monitoring workbook (technical clearance, ethics submission, ethics clearance)"),
    ],
    platform="The student uploads the proposal documents; the adviser signs Form 4 in the platform; the Research Coordinator records the ethics clearance; the platform checks that the required documents are present, and it suggests panel candidates and schedules the defense (see 4.16).",
    platform_diff="The platform checks that documents are present, not their validity. The platform's rule for the month after the defense for ethics review (PRP-08) is not enforced as a deadline. The platform has no step for Form 4.2 and the co-author contribution.",
)

FINAL = Process(
    num="4.14", key="FIN",
    title="Final defense (closed-door and public)",
    purpose="To have the completed thesis or dissertation examined in a closed-door final defense and, for students admitted from August 2020, in a public final defense.",
    who=["Student", "Research adviser", "Research Coordinator", "Panel chair and panel members", "GS Office", "Associate Dean and Dean (copied on the public announcement)"],
    trigger="The student has completed the study, has ethics clearance, and the adviser endorses the final manuscript.",
    preconditions=["Ethics clearance.", "The manuscript has been given to the panel members before the schedule is set (FIN-05).", "Students admitted before August 2020 do not do the public final defense (FIN-16)."],
    steps=[
        ("Student", "Tells the adviser, with the final manuscript, that the student is ready for the closed-door final defense.", "Final manuscript", NS),
        ("Research adviser", "Reviews the manuscript and accomplishes Form 4 with e-signature.", "Form 4", NS),
        ("Student and adviser", "Arrange the target date with the panel; the manuscript must already be with the panel. The adviser emails Form 4, the Ethics Clearance and the manuscript to the Research Coordinator.", "Form 4; ethics clearance", "At least 2 weeks before the defense; panel has 2 weeks to review (14-Day Rule)"),
        ("Research Coordinator", "Emails Form 6, Comments Sheet for Final Defense, and Form 7, Evaluation Sheet for Final Defense, to the panel.", "Forms 6, 7 (blank)", NS),
        ("Panel chair", "Reserves the room through the GS Office, emails the venue, and hosts the defense. The same panel takes part.", "Venue", "Before the defense"),
        ("Panel", "Discusses the manuscript without student and adviser; the student presents; the adviser records comments; the panel deliberates and announces pass, pass with minor revisions, or provisional pass with major revisions (subject to re-defense).", "Result", "At the defense"),
        ("Adviser", "If the student has a provisional pass and no re-defense is recommended, accomplishes Form 8 and emails it to the GS Research Coordinator.", "Form 8", NS),
        ("Panel members / panel chair", "Each member accomplishes Form 6 (to the chair) and Form 7 (to the Research Coordinator); the chair emails all Forms 6 and the consolidated comments to the Research Coordinator, adviser and student.", "Forms 6, 7", "Within the first working day after the defense"),
        ("Student", "Settles the panel fees and emails the proof to the GS mailbox.", "Payment proof", "Within the first working day"),
        ("Student (admitted August 2020 onward)", "Is given two to four weeks to prepare and apply for the public final defense; the adviser reviews compliance (Form 6 with Action Taken and page numbers) and the student and adviser agree a date with the panel.", "Form 6 (Action Taken; page numbers)", "2 to 4 weeks"),
        ("Research adviser", "Emails Form 4.3, Endorsement for Public Defense, fully accomplished with the panel members' e-signatures and the date they received the revised manuscript, to the Research Coordinator.", "Form 4.3", "At least 2 weeks before the defense; application 5 days before for posting (conflict, OQ-23)"),
        ("GS Office / Research Coordinator", "Reserves the venue; the Research Coordinator prepares the announcement, sends it to adviser, student, panel and, in copy, to the Associate Dean and Dean, and posts it on the Graduate School official Facebook page with a pre-registration link; campus entry is processed with the GS Office.", "Public announcement", NS),
        ("Panel chair", "Gives a brief orientation; the student presents for 30 minutes; questions follow (the audience may ask); the panel deliberates; the chair announces the result and the audience leaves; the panel may then emphasize comments not yet addressed.", "Forms 6 and 7", "At the defense"),
    ],
    rules=[
        R("FIN-01", "Final decisions are pass, pass with minor revisions, and provisional pass with major revisions (subject for re-defense).", [H("p. 66"), P("Closed-door Final Defense, Part II")], OFFICIAL),
        R("FIN-02", "The adviser emails Form 4, the Ethics Clearance and the manuscript to the Research Coordinator at least two weeks before the defense.", [H("p. 65"), P("Closed-door Final Defense, Part I (Form 4 submission)")], OFFICIAL),
        R("FIN-03", "14-Day Rule: \"At least fourteen (14) days, inclusive of weekends, from the date the panel members of the oral defense received their copies of the thesis/dissertation to the date of the oral defense.\"", [H("p. 66"), P("Closed-door Final Defense, Part I note")], OFFICIAL),
        R("FIN-04", "The same set of panel members takes part in the closed-door final defense.", [H("p. 66"), P("Closed-door Final Defense, Part I (same panel)")], OFFICIAL),
        R("FIN-05", "The panel members must not agree with the proposed schedule without the revised manuscript; the manuscript must already have been given to the panel before the date is set.", [H("p. 65"), P("Closed-door Final Defense, Part I note")], OFFICIAL),
        R("FIN-06", "If a provisional pass with major revisions is given and the panel recommends a re-defense, the student follows the same protocol for the final defense afterward; the same amount of fees applies to the re-defense.", [H("p. 67"), P("Closed-door Final Defense, Part II note")], OFFICIAL),
        R("FIN-07", "If a provisional pass with major revisions is given but no re-defense is recommended, the student complies with the corrections; once the revised manuscript is given to the panel for approval the 14-Day Rule applies; the adviser accomplishes Form 8 and emails it to the GS Research Coordinator.", [H("p. 67"), P("Closed-door Final Defense, Part II")], OFFICIAL),
        R("FIN-08", "A student who fails to meet the recommendations of all the panel members at a given time is advised to re-defend following the same protocol.", [H("p. 67"), P("Closed-door Final Defense, Part II")], OFFICIAL),
        R("FIN-09", "A provisional pass with major revisions must be reflected in Form 6 and agree with the score in Form 7: for a thesis the score is below 85; for a dissertation the score is below 90.", [H("p. 67"), P("Closed-door Final Defense, Part II note")], OFFICIAL),
        R("FIN-10", "Each panel member accomplishes Form 6 and emails it to the panel chair, and accomplishes Form 7 and emails it to the Research Coordinator, within the first working day after the defense (the Protocol adds that the research adviser also accomplishes Form 7); the chair emails all Forms 6 and the consolidated comments to the Research Coordinator, adviser and student within the same time.", [H("p. 67"), P("Closed-door Final Defense, Part III")], OFFICIAL),
        R("FIN-11", "For students admitted on August 2020 and onwards, the student is given two to four weeks to prepare and apply for the public final defense.", [H("p. 71"), P("Closed-door Final Defense, Part IV")], OFFICIAL),
        R("FIN-12", "Form 4.3 must be fully accomplished with the e-signature of the panel members and the date the panel received the revised manuscript.", [H("pp. 72-73"), P("Public Defense, Part I (Form 4.3 notes)")], OFFICIAL),
        R("FIN-13", "Form 6 must state the Action Taken by the student to address each comment and the specific page number where the improvement appears.", H("p. 72"), OFFICIAL),
        R("FIN-14", "Application for the public final defense must be made 5 days before the preferred schedule for posting purposes; Form 4.3 must be submitted at least two weeks before the date of the defense. (The two periods conflict; see OQ-23.)", [H("pp. 72-73"), P("Public Defense, Part I (Form 4.3 notes)")], OFFICIAL),
        R("FIN-15", "The announcement of the public defense is posted on the Graduate School Official Facebook Page with an embedded pre-registration link; the Research Coordinator coordinates campus entry with the GS Office.", [H("p. 73"), P("Public Defense, Part I (announcement and pre-registration)")], OFFICIAL),
        R("FIN-16", "Students enrolled (admitted) before August 2020 are not required to do a public final defense; instead, after the closed-door final defense, the student presents at a research conference.", [H("pp. 68-69"), P("Closed-door Final Defense, Part III note")], OFFICIAL),
        R("FIN-17", "In the public final defense the student has 30 minutes to present; the Handbook adds another 30 minutes for questions and answers, and the audience may ask questions. Panel members must have Form 6 in hand to check compliance.", [H("p. 73"), P("Public Defense, Part II")], OFFICIAL),
        R("FIN-18", "Only the panel chair submits the defense verdict and the record of the result.", N("July 20 checklist, item 48"), PROPOSED),
    ],
    exceptions=[
        "Provisional pass with major revisions: re-defense or compliance with Form 8 (FIN-06, FIN-07).",
        "Panel members disagree on whether the recommendations were met: the student re-defends (FIN-08).",
        "Public defense audience: the audience leaves the room after the result is announced and the panel may emphasize unaddressed comments in private (Handbook 2022-2023, p. 73).",
        "Final defense fee amounts are not known (OQ-27). The time available to submit the revised manuscript after a pass with minor revisions is not stated.",
    ],
    records=[
        ("Form 4, Form 4.3 and the manuscript", "Research Coordinator; research monitoring workbook (endorsement for final defense, schedule of final defense, schedule of public defense)"),
        ("Forms 6, 7 and 8", "Research Coordinator; student; adviser"),
        ("Public announcement", "Graduate School Facebook page; Associate Dean and Dean (copy)"),
    ],
    platform="The adviser endorses the final defense in the platform; the platform checks that the required documents are present, the panel is complete and the schedule is confirmed with the lead time (14 days for the final defense, 5 for the public defense); the panel chair records the verdict.",
    platform_diff="The platform applies a 14-day lead time for the final and a 5-day lead time for the public defense. The Handbook requires both five days for posting and two weeks for Form 4.3 (OQ-23). The platform does not record the score on Form 7 or the two tracks (before and after August 2020) (OQ-40).",
)

COMPLETION = Process(
    num="4.15", key="CMP",
    title="Revisions and completion",
    purpose="To have the final manuscript approved by the panel, scanned for similarity (Turnitin), edited, bound and submitted with the approval sheet, and to record the conference and publication requirements.",
    who=["Student", "Research adviser", "Panel members", "Turnitin desk", "Editor", "GS Office", "Research ethics office (copy)", "Research Committee", "Publication and Engagement Office"],
    trigger="The final defense is passed (with or without minor or major revisions).",
    preconditions=["The panel's comments have been addressed in the revised manuscript."],
    steps=[
        ("Student", "Polishes the paper by addressing the panel's comments and emails the manuscript to the panel members for approval before Turnitin scanning and editing.", "Revised manuscript", "14-Day Rule applies"),
        ("Panel members", "Email the student confirming initial approval of the final manuscript.", "Approval emails", NS),
        ("Research adviser", "Verifies that the panelists' recommendations are reflected in the manuscript, then endorses it for Turnitin scanning and editing.", "Adviser endorsement", NS),
        ("Student / Turnitin desk", "Requests a Turnitin scan by email; a similarity index rating (SIR) of not more than 15% is required.", "Turnitin certificate", NS),
        ("Student / Editor", "Chooses an editor from the pool affiliated with the University so that the USLS IRF is employed, applies the corrections and presents the revised paper to the editor, who issues Form 9, Editor Certification.", "Form 9", "14-Day Rule applies to the editor's review"),
        ("Student", "Sends the soft copy of the final manuscript, a screenshot of the panel members' approval emails, the Ethics Clearance, the Turnitin certificate and the Editor's certification to the GS Office and the research ethics office.", "Completion documents", "Within the period set by the office (OQ-26)"),
        ("GS Office", "Coordinates with the panel members and advisers for the accomplishment of Form 10, Approval Sheet.", "Form 10", NS),
        ("Student", "Submits the bound copies and the CD with the signed approval sheets as part of the requirements for the diploma, TOR and other documents.", "Bound copy; CD", NS),
        ("Student", "Presents the thesis or dissertation at a research conference (Graduate School Research Conference or external) and submits the certificate of presentation if external.", "Certificate of presentation", "May be submitted after the bound copies and CD"),
        ("Student / Research Committee / Dean", "Publication: chooses a journal from the approved PEO list, accomplishes Form 12 (and Form 11 if a co-author was pre-identified), emails the manuscript, ethics clearance and forms to the Research Coordinator for review by the Research Committee; the Dean approves; the student submits to the journal and later files Form 13 with the copy of the journal or certificate.", "Forms 11, 12, 13", NS),
    ],
    rules=[
        R("CMP-01", "After the student revises the paper, the manuscript is emailed to the panel members for their approval before Turnitin scanning and editing; the 14-Day Rule is applied, and the panel members then email the student confirming their initial approval.", [H("p. 68"), P("Closed-door Final Defense, Part III-IV")], OFFICIAL),
        R("CMP-02", "The adviser verifies that the panelists' recommendations are reflected in the manuscript and then endorses it for Turnitin scanning and editing.", P("Closed-door Final Defense, Part III (adviser verification)"), OFFICIAL),
        R("CMP-03", "The final draft undergoes Turnitin scanning; a similarity index rating (SIR) of not more than 15% is required before the paper goes to the editor.", [H("p. 68"), P("Closed-door Final Defense, Part III")], OFFICIAL),
        R("CMP-04", "The student chooses from the pool of editors affiliated with the University so that the USLS IRF is employed; the 14-Day Rule applies to the editor; the editor gives Form 9, Editor Certification, once corrections are carried out.", [H("p. 68"), P("Closed-door Final Defense, Part III")], OFFICIAL),
        R("CMP-05", "The student sends the soft copy of the final manuscript to the GS Office, copy furnished to the research ethics office, with the panel approval emails, ethics clearance, Turnitin certificate and editor's certification, within the period set by the office, to inform the office that the manuscript is ready for hard-bound reproduction.", H("p. 68"), OFFICIAL),
        R("CMP-06", "The GS Office coordinates with the panel members and advisers for the accomplishment of Form 10, Approval Sheet.", [H("p. 68"), P("Closed-door Final Defense, Part III")], OFFICIAL),
        R("CMP-07", "The student submits the bound copies and CD with the signed approval sheets as part of the requirements for the diploma, TOR and other related documents.", [H("p. 68"), P("Closed-door Final Defense, Part III")], OFFICIAL),
        R("CMP-08", "The student presents the thesis or dissertation at a research conference (the Graduate School Research Conference or an external one); the certificate of presentation for an external conference may be submitted after the bound copies and CD. Only graduating students present at the Graduate School Research Conference and join the graduation ceremony.", [H("pp. 68-69, 74"), P("Public Defense, Part III note")], OFFICIAL),
        R("CMP-09", "Publication: the student chooses a journal from the list of the Publication and Engagement Office and accomplishes Form 12 (Scopus, ISI and Web of Science for PhD; peer-reviewed journals for MA students); the manuscript, ethics clearance (if applicable), Form 11 (if applicable) and Form 12 go to the GS Research Coordinator for review by the Research Committee (Research Coordinator, Academic Coordinator, Associate Dean and the external expert); the Dean approves; the student then files Form 13 with the copy of the journal or the certificate of publication.", H("p. 75"), OFFICIAL),
        R("CMP-10", "The student can only be declared a graduate and join the graduation ceremony once Form 13 and a copy of the journal or certificate of publication has been submitted.", H("p. 75"), OFFICIAL),
        R("CMP-11", "The published journal must include the authorship affiliation in the sample format given in the Handbook.", H("p. 75"), OFFICIAL),
        R("CMP-12", "The best thesis or dissertation award requires a cut-off score of 96 points; the chairman of the committee or the Dean submits the work to the committee and approval by the majority is required.", H("pp. 76-77"), OFFICIAL),
        R("CMP-13", "The office checks that each completion document is present and that the Turnitin certificate shows a rating of 15% or below; it does not verify the content of the documents.", N("July 20 checklist, item 42; Platform (current build)"), PROPOSED),
    ],
    exceptions=[
        "SIR above 15%: the paper cannot go to the editor (CMP-03); what the student must do next is not described in the sources.",
        "External conference: the certificate of presentation is submitted after the bound copies (CMP-08).",
        "The student enrolled before August 2020: presents at a conference instead of a public defense (FIN-16).",
        "Publication: the Protocol supplied is the version without the publication protocol; the Handbook's publication procedure applies (OQ-25).",
    ],
    records=[
        ("Turnitin certificate; Form 9; Form 10; panel approval emails; ethics clearance", "GS Office; research monitoring workbook (Turnitin scan certificate, editor's certification, final approval sheet)"),
        ("Bound copies and CD", "GS Office; Library"),
        ("Forms 11, 12, 13 and proof of publication", "Research Coordinator; research monitoring workbook (publication)"),
    ],
    platform="The platform keeps a completion checklist of five items (soft copy of the final manuscript, panel approval emails, Turnitin certificate with SIR not more than 15%, Form 9, Form 10). It marks research completion when all five are present.",
    platform_diff="The platform does not record the bound copies, the CD, the conference presentation or the publication forms (Forms 11 to 13), and so cannot yet show the Handbook's publication requirement for graduation (OQ-25).",
)

SCHEDULING = Process(
    num="4.16", key="SCH",
    title="Defense scheduling and rescheduling",
    purpose="To set a date, time, venue or meeting link for a defense with the panel and adviser, and to handle changes.",
    who=["Student", "Research adviser", "Research Coordinator", "GS Office", "Panel chair and panel members"],
    trigger="The student is ready for a defense and the documents and panel are in place.",
    preconditions=["A panel is nominated.", "The lead time in the rules below can be met."],
    steps=[
        ("Student / adviser", "Agree a target date with the panel members (title: GS Office coordinates the panel; proposal and final: the student and adviser agree with the panel).", "Form 4 (schedule)", "See lead times below"),
        ("Student (platform)", "Sends a scheduling request with a preferred date and onsite or online mode.", "Scheduling request", NS),
        ("Research Coordinator", "Requests the adviser's and panel members' availability, combines the responses, confirms onsite or online, and proposes a schedule to the student.", "Availability; proposed schedule", NS),
        ("Student", "Accepts the proposal, or asks for a revision with new preferred dates.", "Acceptance / reschedule request", NS),
        ("Research Coordinator", "Finalizes the schedule and notifies the adviser and panel.", "Final schedule", NS),
        ("Panel chair / GS Office", "Reserves the venue through the GS Office or prepares the online details, and tells student, adviser and panel.", "Venue or meeting link", "Before the defense"),
        ("Research Coordinator", "Sends the forms for the defense to the panel.", "Forms", NS),
    ],
    rules=[
        R("SCH-01", "For the title defense the GS Office coordinates with the panel members about the proposed schedule; the Research Coordinator informs the panel and the student of the date and time.", [H("p. 60"), P("Title Defense, Part I, steps 5-6")], OFFICIAL),
        R("SCH-02", "For the proposal and final defenses the student and the research adviser agree with the panel members on the date and time, and the agreed schedule is indicated in Form 4.", [H("pp. 63, 65"), P("Proposal Defense, Part I (agreed schedule)")], OFFICIAL),
        R("SCH-03", "Lead times: title defense application at least two weeks before the defense; Form 4 at least two weeks before the proposal or final defense; the panel has two weeks to review the manuscript; under the 14-Day Rule at least fourteen days, inclusive of weekends, pass from the date the panel receives the manuscript to the defense.", [H("pp. 59, 63, 65-66"), P("Closed-door Final Defense, Part I note")], OFFICIAL),
        R("SCH-04", "Public final defense: Form 4.3 must be submitted five days before the preferred schedule for posting purposes (and at least two weeks before the defense according to the same section; OQ-23).", [H("pp. 72-73"), P("Public Defense, Part I (Form 4.3 notes)")], OFFICIAL),
        R("SCH-05", "The panel chair coordinates with the GS Office for the venue (proposal and closed-door final defense); the GS Office reserves the venue for the public final defense. For students abroad the defense is online.", [H("pp. 63, 66, 70, 73"), P("Proposal Defense, Part I (venue and students abroad)")], OFFICIAL),
        R("SCH-06", "The panel members must not agree with a proposed schedule without the revised manuscript.", H("p. 65"), OFFICIAL),
        R("SCH-07", "A re-defense follows the same protocol as the original defense.", [H("pp. 64, 66-67"), P("Proposal Defense, Part II (major revisions)")], OFFICIAL),
        R("SCH-08", "Faculty invited to a panel may accept the invitation for the proposed date or mark themselves unavailable (the Associate Dean suggested this).", C("21 July 2026", "Associate Dean's suggestion for panel scheduling"), PROPOSED),
        R("SCH-09", "A defense is confirmed only when all required panel members and the adviser are available on the date and the lead time has passed; the student may ask for a schedule revision with new preferred dates; the reason for a reschedule is recorded.", N("BPM accurate flow, section 9; Platform (current build)"), PROPOSED),
    ],
    exceptions=[
        "A panel member is unavailable: the Research Coordinator proposes other dates (SCH-09). The Protocol does not state a notice period for rescheduling (OQ-28).",
        "A student asks to reschedule after the date is confirmed: not stated in the sources; the notice period, who approves and whether the panel fee changes are open (OQ-28).",
        "A manuscript reaches the panel late: the 14-Day Rule is not met and the panel should not agree to the date (SCH-03, SCH-06).",
    ],
    records=[
        ("Form 4 (schedule), meeting details, reservations", "Research Coordinator; GS Office"),
        ("Schedule entries", "Research monitoring workbook (schedule of title, proposal, final and public defense)"),
    ],
    platform="The platform collects availability from the adviser and the panel, shows the earliest common dates, applies the lead time, lets the student accept or request a revision, and records the confirmed schedule, mode and venue. The panel availability in the demonstration data is sample data; the platform is not connected to a calendar.",
    platform_diff="The platform uses a lead time of zero for a title defense, fourteen days for the proposal and final defense and five days for the public defense. The Protocol asks two weeks for the title defense and two weeks for Form 4.3 (OQ-23). The notice period for rescheduling is not defined in any source (OQ-28).",
)
