"""Chapter 6: open questions for validation.

Each question has: id, topic, kind (Conflict / Silent / Practice differs), what the
sources say, the question, the options, and the rules it affects.  The builder
adds a blank answer line for the stakeholder.
"""

from __future__ import annotations

QUESTIONS = [
    dict(id="OQ-01", topic="Withdrawal of subject: how long is it allowed and what does it cost?", kind="Conflict",
         says=[
             "Handbook 2022-2023, pp. 49, 51: a student may withdraw subjects until the second week from the start of classes; 10% of the total amount due for the term is charged in the first week and 20% in the second week.",
             "Consultation 29 July 2026 (the group's account of the Associate Dean's answer): withdrawal is possible before classes start or in the first week; Consultation 21 July 2026 describes withdrawal as the official, no-mark kind of leaving a subject.",
             "Platform: before classes begin or in the first seven calendar days, with no academic penalty and no fee shown.",
         ],
         question="Which window and which fee apply to a withdrawal of a subject?",
         options=["A. The Handbook as written: until the end of the second week, 10% in week 1 and 20% in week 2.", "B. Before classes begin and the first week only, with the fee to be stated by the Graduate School.", "C. Two steps: no academic mark in the first seven days, and the Handbook's 10% and 20% fees through the second week."],
         affects=["WD-01", "WD-02", "WD-13", "WD-14"]),
    dict(id="OQ-02", topic="What does a withdrawal before the first day of classes cost?", kind="Silent",
         says=["Handbook 2022-2023, pp. 49, 51: states a 10% charge \"within the first week of classes\" but nothing about a request made before classes begin."],
         question="Is there a charge when a student withdraws a subject after enrolling but before classes start?",
         options=["A. No charge.", "B. 10% as in the first week.", "C. The Business Office decides case by case."],
         affects=["WD-02", "WD-14"]),
    dict(id="OQ-03", topic="After the second week: may a student still withdraw from one subject, and what is it called and marked?", kind="Silent",
         says=[
             "Handbook 2022-2023, p. 49: \"The student retains the right to withdraw all subjects at any time of the semester thereafter but will pay the full enrolment fees.\" It speaks of all subjects, not one.",
             "Handbook 2022-2023, p. 53: grade symbols W (Withdrawn) and D (Dropped); a leave taken in the second half of the semester gives W for all courses.",
             "Consultation 21 July 2026: dropping is leaving a subject in the middle of the semester; withdrawal is the official, earlier kind.",
         ],
         question="After the second week, what may a student do with a single subject, and what mark and fee apply?",
         options=["A. Only a leave of absence or withdrawal of all subjects; single subjects cannot be withdrawn.", "B. A single subject may be dropped (mark D) with full fees.", "C. A single subject may be withdrawn (mark W) with full fees, or fees to the last month of attendance for a justifiable reason."],
         affects=["WD-03", "WD-04", "DRP-10"]),
    dict(id="OQ-04", topic="Does a withdrawal or a drop need approval, and may it be refused?", kind="Conflict",
         says=[
             "Handbook 2022-2023, p. 49: for a withdrawal the student writes a letter and seeks approval from the Dean.",
             "Consultation 29 July 2026 (account of the Associate Dean): the Dean decides with discretion; usual reasons to deny are a late request or an unsupported reason.",
             "Consultation 15 and 29 July 2026 (capstone adviser sessions, not Graduate School staff): dropping and withdrawing are a student's right and are not denied.",
             "Consultation 21 July 2026: for dropping, the student talks to the Academic Coordinator and, once agreed, the subject is tagged dropped.",
         ],
         question="Who approves a withdrawal, who approves a drop, and on what grounds may a request be refused?",
         options=["A. The Dean approves every withdrawal and may refuse; a drop needs no approval.", "B. Neither needs approval; the Graduate School only records them.", "C. Withdrawal needs the Dean's approval; a drop needs the Academic Coordinator's agreement."],
         affects=["WD-06", "WD-13", "DRP-07", "DRP-09"]),
    dict(id="OQ-05", topic="Dropping: procedure, forms, and how the Graduate School finds out", kind="Silent",
         says=[
             "Handbook 2022-2023: the only dropping rule is the automatic drop for absences (p. 52); no student-requested drop procedure or form is described; the Withdrawal Form is named (p. 49) but not supplied.",
             "Consultation 21 July 2026: the student talks or writes to the Academic Coordinator; the Graduate School drops in AIMS as well as in its own record.",
         ],
         question="What is the drop procedure, which form (if any) is used, who informs the professor and who records the drop in AIMS? How is the Graduate School informed if a student stops attending without telling anyone?",
         options=["A. Email or conversation with the Academic Coordinator only; no form.", "B. A written form, to be supplied by the Graduate School.", "C. The professor reports drops to the Academic Coordinator."],
         affects=["DRP-07", "DRP-08", "DRP-09"]),
    dict(id="OQ-06", topic="DRP grade and program consequences", kind="Conflict",
         says=[
             "Handbook 2022-2023, p. 52: an automatic drop for absences gives the grade DRP with a 5.0.",
             "Handbook 2022-2023, p. 53: the grading table lists D (Dropped), not DRP.",
             "Handbook 2022-2023, p. 54: a 5.0 means the student is automatically dropped from the program; failure in any subject means no re-admission.",
         ],
         question="Is DRP the same as D? Does a DRP with 5.0 count as a failure that drops the student from the program?",
         options=["A. DRP is a failure; the retention rule applies.", "B. DRP is recorded as a drop only; the retention rule does not apply.", "C. To be decided by the Dean case by case."],
         affects=["DRP-03", "DRP-05", "DRP-06"]),
    dict(id="OQ-07", topic="Change or add of subject after the first week", kind="Silent",
         says=["Handbook 2022-2023, pp. 48-49: change of subject and adding of subjects are allowed during the first week only; no fee or exception is stated."],
         question="Is any exception possible after the first week, who may grant it, and is there a fee for changing or adding?",
         options=["A. No exception.", "B. The Dean may allow an exception for a stated reason.", "C. Fees to be stated by the Business Office."],
         affects=["CRS-01", "CRS-02", "CRS-03"]),
    dict(id="OQ-08", topic="How are \"first week\" and \"second week\" counted?", kind="Silent",
         says=["Handbook 2022-2023, pp. 49, 52: \"first week of classes\", \"second week\" and \"attendance counted from the first regular class meeting\"; no calendar rule is given.", "Platform: seven calendar days from the start date of the semester."],
         question="Are the weeks counted from the first day of classes of the semester, or from each subject's first class meeting? Do summer terms follow the same weeks?",
         options=["A. Calendar days from the official first day of classes.", "B. From the first class meeting of each subject.", "C. Another rule, to be stated."],
         affects=["WD-01", "WD-02", "CRS-01", "CRS-02", "ENR-03"]),
    dict(id="OQ-09", topic="Leave of absence: length and number of leaves", kind="Conflict",
         says=[
             "Handbook 2022-2023, p. 52: a leave may be approved for one year and renewed for at most another year.",
             "Platform: one or two consecutive semesters, and fewer than four earlier approved leaves; the platform's help text says up to four semesters in total.",
         ],
         question="How long may a leave be, is the two-year limit counted per leave or over the whole program, is a year two semesters or three terms, and is there a maximum number of leaves?",
         options=["A. One year, renewable once for another year, per leave; no limit on the number of leaves.", "B. A total of two years over the whole program.", "C. Two semesters, renewable once, with a maximum number of leaves to be stated."],
         affects=["LOA-03", "LOA-13"]),
    dict(id="OQ-10", topic="Does leave of absence count toward maximum residence?", kind="Conflict",
         says=[
             "Handbook 2022-2023, p. 55: a master's program must be finished within seven academic years including leave of absence; a doctorate within nine including leave.",
             "Platform: the residency clock is paused during an approved leave.",
         ],
         question="Is the leave included in the maximum residence as the Handbook says?",
         options=["A. Yes, included (Handbook).", "B. No, the clock is paused.", "C. The first year of a leave is excluded."],
         affects=["LOA-10", "RES-07", "RES-09"]),
    dict(id="OQ-11", topic="Leave of absence: filing deadline and start term", kind="Conflict",
         says=[
             "Handbook 2022-2023, p. 52: \"LOA must be done on or before the deadline\" (no date is given).",
             "Handbook 2022-2023, p. 53: a leave is allowed in the second half of a semester (class standing W, no refund) but not within two weeks before the last day of classes.",
             "Platform: the leave must start in a future term; a leave cannot be filed for a semester already started.",
         ],
         question="What is the deadline to file a leave, and may a leave start in the semester already running?",
         options=["A. Deadline is the end of the enrollment period; the leave starts in a future term only.", "B. As in the Handbook: a leave may start during the semester until two weeks before the last day of classes, with W and no refund in the second half.", "C. Another rule."],
         affects=["LOA-04", "LOA-08", "LOA-09", "LOA-13"]),
    dict(id="OQ-12", topic="Written letter or structured form for leave, withdrawal and readmission; can a pending request be withdrawn?", kind="Silent",
         says=["Handbook 2022-2023, pp. 49, 52-53: the requests are letters to the Dean or the Registrar.", "Platform: structured forms with a reference; a pending leave request cannot be withdrawn by the student (Consultation 20 July 2026)."],
         question="May a structured form replace the letter, and may a student withdraw a pending request?",
         options=["A. Letter only.", "B. The platform form is accepted as the written request.", "C. Form plus a signed letter attached."],
         affects=["LOA-02", "LOA-12", "WD-06", "RDM-01"]),
    dict(id="OQ-13", topic="Readmission requirements", kind="Conflict",
         says=[
             "Handbook 2022-2023, p. 45: clearance from the Business Office, an interview (reason for delay, residency requirements), evaluation of subject and grade requirements, and an Advise Slip from the Dean.",
             "Platform: structured return intention, updated study plan, program or adviser consultation, and no pending accountability.",
             "Consultation 20 July 2026: the adviser asked whether a readmitted student is automatically eligible to enroll; no answer is recorded.",
         ],
         question="Which list applies, who interviews and evaluates, and is a readmitted student automatically cleared to enroll?",
         options=["A. The Handbook's four requirements only.", "B. The platform's four items only.", "C. Both lists; the interview and evaluation by the Academic Coordinator."],
         affects=["RDM-02", "RDM-05"]),
    dict(id="OQ-14", topic="AWOL: who declares it and what follows", kind="Silent",
         says=["Handbook 2022-2023, p. 53: a student who withdraws without a formal leave is AWOL, and registration privileges are curtailed or withdrawn; nothing is said about who declares it, when, or whether AWOL counts toward maximum residence.", "Platform: AWOL is flagged from source evidence and cannot be declared manually."],
         question="Who declares AWOL, after how long, is the Registrar told, and does the AWOL period count toward maximum residence?",
         options=["A. The Dean declares it after one semester with no enrollment and no approved leave; the period counts toward maximum residence.", "B. The Registrar's record is the only basis; the Graduate School only records it.", "C. Another rule."],
         affects=["AWL-01", "AWL-04", "AWL-05", "AWL-06"]),
    dict(id="OQ-15", topic="Residency enrollment: fee, deadline and number of semesters", kind="Silent",
         says=["Handbook 2022-2023, pp. 48, 56: registration for residence is done within the semester; no fee and no maximum number of residency semesters is stated."],
         question="What is the fee, what is the registration deadline, and how many residency semesters may a student take?",
         options=["A. As for a regular semester; no limit other than maximum residence.", "B. A fixed number of semesters per purpose, to be stated."],
         affects=["RES-01", "RES-02", "RES-04"]),
    dict(id="OQ-16", topic="Maximum residence: how it is measured and who approves the extension", kind="Silent",
         says=["Handbook 2022-2023, pp. 54-55: candidacy within three (master's) or five (doctorate) academic years from admission, completion within five or seven, an extension of up to two years with a graded six-unit refresher course, and absolute limits of seven and nine academic years; no rule says whether summer terms count or who approves an extension.", "Platform: counts calendar years from the entry year, approximately."],
         question="How is an academic year counted (summer terms?), and who approves an extension and the refresher course?",
         options=["A. Academic years from the date of admission; the Dean approves the extension.", "B. Academic years from the date of first enrollment; the Academic Coordinator recommends and the Dean approves.", "C. Another rule."],
         affects=["RES-05", "RES-06", "RES-07", "RES-08", "RES-09"]),
    dict(id="OQ-17", topic="Comprehensive examination: before or after the title defense and the adviser?", kind="Conflict",
         says=[
             "Handbook 2022-2023, p. 57: after the student passes the comprehensive examination the student confers with the Dean for an adviser and is advanced to candidacy.",
             "Handbook 2022-2023, p. 58: an adviser may be assigned while the student is still taking courses.",
             "Research Protocol AY2024-2025: silent on the comprehensive examination.",
             "Platform: a title defense application is accepted only after the examination is passed and all curriculum subjects are complete.",
         ],
         question="In what order must the comprehensive examination, the adviser designation and the title defense happen, and does it differ for thesis and non-thesis tracks?",
         options=["A. The examination must be passed before the title defense and the adviser.", "B. An adviser and the title defense may come during coursework; the examination only before the final defense.", "C. Different order for thesis and non-thesis students."],
         affects=["CEX-10", "CEX-13", "ADV-08"]),
    dict(id="OQ-18", topic="Comprehensive examination: missing rule and evaluator", kind="Silent",
         says=["Handbook 2022-2023, p. 57: the sentence beginning \"The student who failed to take the Comprehensive Exam on the scheduled dates within the semester\" is cut off in the copy supplied.", "Handbook 2022-2023, p. 56: master's students are evaluated by the Graduate School Academic Coordinators; doctorate students by the College Deans."],
         question="What is the consequence of not taking the examination on the scheduled dates, and who evaluates doctorate students for eligibility?",
         options=["A. The fee is forfeited and the student re-enrolls in residency for the next examination.", "B. Doctorate students are evaluated by the Graduate School Dean."],
         affects=["CEX-03", "CEX-07"]),
    dict(id="OQ-19", topic="Who approves the designation of the research adviser?", kind="Conflict",
         says=[
             "Handbook 2022-2023, p. 58: the Dean appoints the adviser, with the approval of the program adviser and the Dean, giving primary importance to the student's choice.",
             "Handbook 2022-2023, p. 59: the Dean, the Associate Dean and the Research Coordinator make the final decision.",
             "Research Protocol AY2024-2025, Designation of the Research Adviser: the Research Coordinator emails Form 3 to the Dean for deliberation; the Research Coordinator, Associate Dean and Dean sign.",
         ],
         question="Who decides, and who signs: the Dean alone, or the Dean, Associate Dean and Research Coordinator together? Is the program adviser's approval needed?",
         options=["A. The Dean, Associate Dean and Research Coordinator decide together; the program adviser is consulted.", "B. The Dean decides on the Research Coordinator's recommendation.", "C. Another route."],
         affects=["ADV-05", "ADV-06", "ADV-09"]),
    dict(id="OQ-20", topic="Adviser eligibility and the limit on advisees", kind="Conflict",
         says=[
             "Handbook 2022-2023, p. 58: a Graduate School faculty with a doctoral degree aligned with the discipline and at least one refereed publication or recognized output; more than five advisees only with the Dean's approval.",
             "Handbook 2022-2023, p. 59: a maximum of five advisees per semester.",
             "Research Protocol AY2024-2025: a PhD for PhD students and at least PhD units for MA students; a maximum of five active advisees for the current academic year.",
         ],
         question="Which eligibility rule applies to MA advisers, and is the limit five per semester or five active advisees per academic year?",
         options=["A. The Protocol (more recent).", "B. The Handbook.", "C. Both apply."],
         affects=["ADV-02", "ADV-03", "ADV-04", "ADV-05"]),
    dict(id="OQ-21", topic="Adviser nomination by the student and acceptance by faculty", kind="Practice differs",
         says=["Consultation 21 July 2026: the student nominates three faculty and each can accept or decline.", "Handbook 2022-2023 and Research Protocol AY2024-2025: Form 3 names an adviser; neither mentions three nominees or faculty acceptance before the application."],
         question="Is the three-nominee and accept-or-decline step the office's practice? Is it written on Form 3?",
         options=["A. Yes, it is practice and should be written into the Protocol.", "B. No, Form 3 names one adviser who has already agreed."],
         affects=["ADV-16", "ADV-17"]),
    dict(id="OQ-22", topic="Who approves the external panel member?", kind="Conflict",
         says=["Handbook 2022-2023, p. 63: the adviser's recommendation is subject to the approval of the GS office.", "Research Protocol AY2024-2025, Proposal Defense, Part I: subject to the approval of the GS Research Committee (Dean, Associate Dean, Academic Coordinator, Research Coordinator)."],
         question="Which body approves the external panel member?",
         options=["A. GS Research Committee.", "B. GS Office.", "C. The Research Coordinator on the Dean's behalf."],
         affects=["PRP-04", "TTL-02"]),
    dict(id="OQ-23", topic="Public final defense: five days or two weeks?", kind="Conflict",
         says=["Handbook 2022-2023, pp. 72-73 and Research Protocol AY2024-2025, Closed-door Final Defense, Part IV and Public Defense, Part I: application (Form 4.3) \"must be done 5 days before the preferred schedule for GS posting purposes\"; the same section says \"This must be done at least 2 weeks before the date of defense.\""],
         question="What is the lead time for Form 4.3?",
         options=["A. Five days for posting, and two weeks for the panel to have the manuscript (the 14-Day Rule), both apply.", "B. Five days only.", "C. Two weeks only."],
         affects=["FIN-14", "SCH-03", "SCH-04"]),
    dict(id="OQ-24", topic="Public final defense: presentation and question time", kind="Conflict",
         says=["Handbook 2022-2023, p. 73: the student is given 30 minutes to present, followed by another 30 minutes for questions and answers.", "Research Protocol AY2024-2025, Public Defense, Part II: 30 minutes to present, followed by the deliberation by the panel."],
         question="Is the question time part of the thirty minutes, separate, or not limited?",
         options=["A. 30 minutes present, 30 minutes questions.", "B. 30 minutes present, questions until the panel is ready to deliberate."],
         affects=["FIN-17"]),
    dict(id="OQ-25", topic="Publication and dissemination requirements for graduation", kind="Conflict",
         says=[
             "Handbook 2022-2023, p. 75: Forms 11, 12 and 13; a student can only be declared a graduate and join the ceremony once Form 13 and proof of publication are submitted; Scopus, ISI and Web of Science for PhD, peer-reviewed for MA.",
             "Handbook 2022-2023, p. 77: publication in a Scopus-indexed, Web of Science and ISI journal for those enrolled from AY 2022-2023 onwards; presentation in a public seminar series.",
             "Handbook 2022-2023, pp. 68-69, 74: presentation at a research conference.",
             "Research Protocol AY2024-2025 copy: \"without publication protocol\".",
         ],
         question="Who must publish, in what kind of journal, and what happens to students enrolled before AY 2022-2023 and to MA students? Is the conference and the public seminar series one requirement or two?",
         options=["A. Publication required for all; Scopus/ISI/WoS for PhD and peer-reviewed for MA.", "B. Publication required only for those enrolled from AY 2022-2023 onwards; earlier students only present at a conference.", "C. Another rule."],
         affects=["CMP-08", "CMP-09", "CMP-10", "GRD-08", "GRD-09"]),
    dict(id="OQ-26", topic="Time allowed to send the completion documents", kind="Silent",
         says=["Handbook 2022-2023, p. 68: the student sends the soft copy and documents \"within the period set by the office\"; no period is stated.", "No time limit is stated for revisions after a pass with minor revisions."],
         question="What period has the office set for sending the completion documents, and for revisions after a pass with minor revisions?",
         options=["A. A number of days after the defense, to be stated.", "B. By the graduation review window."],
         affects=["CMP-05", "FIN-07"]),
    dict(id="OQ-27", topic="Defense fee amounts", kind="Silent",
         says=["Research Protocol AY2024-2025 copy: the fee tables for title, proposal and final defense (chair, members, adviser, total) are blank; the Handbook does not state amounts."],
         question="What are the fees per role (chair, panel member, adviser), per program type (project paper, thesis, dissertation) and per defense (title, proposal, closed-door final, public, re-defense)?",
         options=["A. Amounts to be supplied by the Graduate School.", "B. Amounts are set each year by the Business Office."],
         affects=["TTL-08", "PRP-09", "FIN-06"]),
    dict(id="OQ-28", topic="Rescheduling a confirmed defense", kind="Silent",
         says=["Handbook 2022-2023 and Research Protocol AY2024-2025: nothing on rescheduling apart from re-defense following the same protocol.", "Group process model: the student may ask for a schedule revision before confirmation."],
         question="What is the notice period to reschedule, who approves, how many times, what happens to the fee, and what if a panel member withdraws?",
         options=["A. Reschedule allowed by the Research Coordinator with at least the lead time.", "B. Rescheduling needs the Dean's approval.", "C. Another rule."],
         affects=["SCH-07", "SCH-09"]),
    dict(id="OQ-29", topic="Practicum: programs, hours, documents and approvers", kind="Silent",
         says=["Handbook 2022-2023, pp. 48, 56: practicum appears only in residency enrollment and in the integrating courses of the Education non-thesis track; no hours or documents are given.", "Platform and the group's notes: Psychology programs and MSGC only; 200 hours; Basic 6, Major 9, Cognate 6 and total 21 units before practicum; MOA and certificates; Academic Coordinator verifies; Dean reviews.", "Group notes: a PhD in Psychology curriculum lists DPSY330 Internship, six units."],
         question="Which programs have a practicum, how many hours does each require, what must be completed first, what documents prove it, and who verifies and accepts it? Should start and end dates and schedules be recorded?",
         options=["A. Psychology programs and MSGC, 200 hours each, as in the platform.", "B. Hours and prerequisites differ by program and will be supplied.", "C. Other programs also have a practicum."],
         affects=["PRC-03", "PRC-04", "PRC-05", "PRC-07", "PRC-09"]),
    dict(id="OQ-30", topic="Graduation review window", kind="Silent",
         says=["Platform: limits graduation selection to the active school year; no opening or closing dates.", "Handbook 2022-2023, p. 77: the student must be officially enrolled in the semester of application for graduation; no dates."],
         question="When does the graduation review window open and close, how are late applicants treated, and what happens to an eligible student who misses the window?",
         options=["A. A fixed window each semester, dates to be supplied.", "B. Open for the whole school year; the Registrar's deadline governs."],
         affects=["GRD-02", "GRD-15"]),
    dict(id="OQ-31", topic="Graduation document checklist", kind="Silent",
         says=["Handbook 2022-2023, p. 77: lists the requirements; Forms 9 and 10 and the Turnitin certificate are completion documents (p. 68).", "Platform: checks the research evidence and a signed application PDF."],
         question="Which documents are always required, is Form 9 or Form 10 always required, does every program need a Turnitin certificate, what clearances apply, is there an official graduation application form, and which office verifies each?",
         options=["A. All documents in the Handbook's completion list for every program.", "B. A program-specific list to be supplied."],
         affects=["GRD-06", "GRD-13", "GRD-14"]),
    dict(id="OQ-32", topic="Registrar acknowledgement and export formats", kind="Silent",
         says=["Platform: exports a file and records that it is ready to send; does not record receipt.", "Group notes: two options are open: A. leave acknowledgement outside the platform; B. record a manual acknowledgement with reference number, date and office."],
         question="Should the Graduate School record the Registrar's acknowledgement? What columns, file names and formats does the Registrar accept for withdrawals and graduation?",
         options=["A. Keep acknowledgement outside the platform.", "B. Record a manual acknowledgement with a reference number and date.", "C. Formats to be supplied by the Registrar."],
         affects=["HND-09", "HND-10", "GRD-16"]),
    dict(id="OQ-33", topic="Who imports the monitoring workbook, from what source and how often?", kind="Practice differs",
         says=["Group process model: the Registrar sends a file to GS staff, who import it (BPM accurate flow, section 1).", "Consultation 29 July 2026 (adviser): if the Academic Coordinator and GS staff work in the same office, the person who holds the file should upload it.", "Consultation 21 July 2026: AIMS cannot be integrated; the office can ask ITS for an Excel export; the Academic Coordinator tags enrolled subjects as students are advised."],
         question="Who imports or updates the monitoring workbook, what is its source (Registrar file, ITS export, the Academic Coordinator's own sheet), and how often is it updated?",
         options=["A. GS staff, each term, from the Registrar's or ITS's file.", "B. The Academic Coordinator, from the AIMS export.", "C. Both, with daily updates by tagging."],
         affects=["ADM-09", "ADM-11", "ADM-12", "ENR-08"]),
    dict(id="OQ-34", topic="Minimum class size: may a subject be opened for one student?", kind="Practice differs",
         says=["Consultation notes (answer attributed to the Associate Dean): the subject-demand cutoff is one student; a need is not automatically an offering.", "Consultation 29 July 2026 (adviser): a school does not open a class for one student; minimum demand means the minimum for the course to open.", "Handbook 2022-2023, p. 48: an undersized class is treated as a special class; the Dean ensures each new batch reaches the minimum number of enrollees."],
         question="What is the minimum number of students to open a subject, and how is a smaller class handled?",
         options=["A. One student counts as a need; the Academic Coordinator decides; a small class is a special class.", "B. A minimum number to be stated; below it a special class or deferral."],
         affects=["CRS-04", "CRS-08"]),
    dict(id="OQ-35", topic="Approval of the offering and assignment of professors", kind="Practice differs",
         says=["Group process model: the Dean approves the offering plan (BPM accurate flow, section 3).", "Consultation 21 July 2026: the Academic Coordinator decides what to offer and who teaches it, using the faculty profile and CV; no mention of the Dean.", "Handbook 2022-2023, p. 48: a special class goes through the Dean to the Vice Chancellor for Academic Affairs."],
         question="Does the Dean approve the offering? How and when does the office learn the professors' availability and preferred subjects?",
         options=["A. The Academic Coordinator decides; the Dean is informed.", "B. The Dean approves every offering plan.", "C. Approval only for special classes."],
         affects=["CRS-07", "CRS-10", "CRS-12"]),
    dict(id="OQ-36", topic="Failures, incompletes and grade timing", kind="Silent",
         says=["Handbook 2022-2023, pp. 49, 54: professors submit grades within one year; an INC is removed within one academic year by submitting the Incomplete Grade Removal Form to the Graduate School Office; all INC means dropped from the rolls.", "Consultation 21 July 2026: failures and incompletes are rare and are reported by faculty to the Academic Coordinator, who tags the status.", "Group notes: grades are visible in AIMS; when they become visible is not known."],
         question="How do failures and incompletes reach the Academic Coordinator, and when in the term break are grades available in AIMS?",
         options=["A. Faculty email the Academic Coordinator; grades are visible before the offering planning.", "B. The Registrar sends a list."],
         affects=["ENR-12", "DRP-12"]),
    dict(id="OQ-37", topic="Alumni seminar, public seminar series and research conference", kind="Silent",
         says=["Handbook 2022-2023, p. 80: graduating students must attend the Alumni seminar; p. 77: presentation in a public seminar series; pp. 68-69, 74: presentation at a research conference."],
         question="Are the public seminar series and the research conference the same event? When must each be completed relative to the ceremony?",
         options=["A. The same event.", "B. Separate requirements."],
         affects=["GRD-08", "GRD-10", "CMP-08"]),
    dict(id="OQ-38", topic="Is the Handbook 2022-2023 still in force?", kind="Silent",
         says=["The only Handbook supplied is 2022-2023. The Protocol is for AY 2024-2025."],
         question="Is there a later Handbook or any memorandum that changes withdrawal, leave, residency, or the defense rules?",
         options=["A. The 2022-2023 Handbook is in force without changes.", "B. A later edition or memos exist and will be supplied."],
         affects=[]),
    dict(id="OQ-39", topic="Names of offices and mailboxes", kind="Conflict",
         says=["Handbook 2022-2023, pp. 23, 65, 68: the Social Research Ethics Committee and Office; one email address is given for ethics review.", "Research Protocol AY2024-2025: RERC and RERO with a different email address; the GS Research mailbox and a separate Turnitin mailbox."],
         question="What is the correct name of the research ethics office and what are the correct mailboxes for ethics review, Turnitin and the Graduate School Office?",
         options=["A. The Protocol's names and addresses are current.", "B. The Handbook's are current."],
         affects=["PRP-08", "CMP-05"]),
    dict(id="OQ-40", topic="Which date decides between the closed-door-only track and the public defense track?", kind="Conflict",
         says=["Handbook 2022-2023, pp. 65, 69: students \"admitted before August 2020\" have no public defense.", "Research Protocol AY2024-2025: students \"enrolled prior to August 2020\"."],
         question="Is the date that of admission or of first enrollment?",
         options=["A. Date of admission.", "B. Date of first enrollment."],
         affects=["FIN-16"]),
    dict(id="OQ-41", topic="Research time limits: what happens when they are exceeded?", kind="Silent",
         says=["Handbook 2022-2023, p. 58: one year from the title defense to defend the proposal; thesis or project paper writing within two years; dissertation within three years; no consequence or extension is stated."],
         question="What is the consequence of exceeding these limits, who may extend them, and how do they relate to the maximum residence?",
         options=["A. The title defense is repeated.", "B. The Dean may extend once.", "C. Another rule."],
         affects=["TTL-09", "RES-10"]),
    dict(id="OQ-42", topic="Project paper panel: external member?", kind="Conflict",
         says=["Handbook 2022-2023, p. 60 and Research Protocol AY2024-2025: a project paper panel is the chair and two members (content and method); an external panel member applies to theses and dissertations.", "Platform: requires an external panel member for a project paper."],
         question="Does a project paper panel include an external member?",
         options=["A. No (Handbook and Protocol).", "B. Yes, for some programs."],
         affects=["TTL-03"]),
    dict(id="OQ-43", topic="Waivers of the two-week rules", kind="Silent",
         says=["Handbook 2022-2023, pp. 59, 63, 65 and Research Protocol AY2024-2025: applications must be made at least two weeks before the defense; no waiver is described.", "Platform: no lead time for a title defense."],
         question="May the Research Coordinator or the Dean accept an application with less notice, and on what grounds?",
         options=["A. No waivers.", "B. The Dean may waive for a stated reason."],
         affects=["TTL-01", "PRP-02", "SCH-03"]),
    dict(id="OQ-44", topic="Are there course prerequisites?", kind="Conflict",
         says=["Handbook 2022-2023, p. 49: a subject may be changed in the first week if the student fails in the \"prerequisite subject\".", "Group notes, July 20 checklist, items 16 and 75 (stakeholder-confirmed answer): there are no ordinary course-to-course prerequisites; eligibility rules apply mainly to the comprehensive examination and the thesis or dissertation."],
         question="Do any subjects have prerequisites, and if so where are they listed?",
         options=["A. No ordinary prerequisites; the Handbook's reference is to a program-specific case, to be named.", "B. Some programs list prerequisites in their curriculum; the lists will be supplied."],
         affects=["ENR-09", "CRS-01"]),
]
